### ISSUE TITLE
add continous online/offline network connectivity check

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#10]
Add a simple continuously displayed "Your device is offline" to last-update-card and on state change a "your device is online" which disappears after 3 seconds.

**Comment by opeeters** [comment]
see e.g.: https://www.joshmorony.com/monitoring-online-and-offline-states-in-an-ionic-application/

**Comment by janschulte** [comment]
Done with commit 92f473cf75cffadc0a39e3f769db86646456ed64
