### ISSUE TITLE
Stuck @ no data connection message

### ISSUE THREAD

**Issue by lodagro** [irceline/aq-mobile-be#100]
Sometimes the app is stuck at `no data connection` message.
It seems it can not recover from a missing data connection. I had to restart to recover.

![screenshot_2019-01-15-16-29-26](https://user-images.githubusercontent.com/1094464/51428198-2b638c00-1c01-11e9-9440-813e9672bda5.png)

**Comment by opeeters** [comment]
Thanks @lodagro  for the feedback. From the statusbar icons it seems that your wifi is connected to your device, but the wifi router probably has an unstable connection to the internet (hence the little question mark). If so, this is related to #98 . Anyhow, this should not happen. We'll fix this asap.. Cheers!

**Comment by opeeters** [comment]
pragmatic solution adding close button: 390a22cfacaef42afcf600ab9e5d2c3be19e68e5
