### ISSUE TITLE
limit the number of user defined locations

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#105]
Limit the number of user defined locations to maximum 5. This should include an alert message being triggered when a user already has 5 locations defined and presses the 'create new location' button: "You can create no more than 5 locations. Please first remove one of the locations here: 'edit current locations' button.

**Comment by janschulte** [comment]
Done with: 34e391423a24106ef425fa601a56023bef65061b

Currently the `current location` is excepted of this limit. So beside the 5 created locations the user can additionally see the current location on the slides.
