### ISSUE TITLE
uniform fitBounds map

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#107]
When going from start page to map view, the belaqi layer is displayed slightly to much south. East-west is adjustable with the `defaultBbox` parameter in `settings.json`. North-south does not respond to changes in `settings.json`. When going to the `NO2` tab, the bounding-box is readjusted when the stations are loaded. This should be more uniform.

**Comment by janschulte** [comment]
Fixed the uniformed behaviour with 91ff35be8053080b487b0b156c372f85498ece43

After adjustments in the settings.json, the app must be rebuild or restarted (`npm start`) to see the results
