### ISSUE TITLE
Add offline Leaflet Tile cache

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#109]
Currently, when going to the map-view with an active network connection, opening all the tabs, deactivating network connectivity, cycling back through the tabs.. all WMS tiles and station icons are gone. This data could perfectly be taken from an app cache on the client side, which would make the app much more usable on e.g. you daily commute when network connectivity might not always be stable.

It would probably be best to do a check whether data which is needed to make maps in correspondence to `lastupdate` in http://www.irceline.be/air/time_app_json.php is present in client cache before sending an unnecessary request to http://geo.irceline.be, not only to spare our servers, but also to avoid unnecessary, expensive mobile data consumption in general.

If http://www.irceline.be/air/time_app_json.php is not available (e.g. due to an unstable data connection), the last available data in accordance with the last successfully received `lastupdate` should be used. We can think of a sensible maximum age later. In general I would think that the cache should only be emptied as soon as new data has been successfully been loaded, but that `lastupdate` cached data is still usable, even 3 days later because the app cache could still hold the provisions for the day.

**Comment by opeeters** [comment]
Maybe have a look at: 
* https://github.com/MazeMap/Leaflet.TileLayer.PouchDBCached

**Comment by SpeckiJ** [comment]
I have implemented the caching of tiles on Android using the suggested PouchDB library in https://github.com/irceline/aq-mobile-be/commit/50ddd2e6b5a84b2d66e771ea680b3ad000741d5e.

Notes:
- Currently the tiles are cached for 24h
- There is no indication apart from the original popup that the app is in "offline-mode". As some maps still work and others not, this is confusing for the user. A permanent visualization that the App is in "offline-mode" is needed
- This still needs to be tested on iOS

**Comment by SpeckiJ** [comment]
https://github.com/irceline/aq-mobile-be/commit/80b8d24b35b88729a9ce3a4a326dd03c2cebeee1 implements a cache clearing routine on app startup.

Currently this routine drops all files until the defined constant maxDocCount is reached + additional 1/3 of maxDocCount (prevent directly overflowing again). As the routine only runs on startup, the cache size of the App might get larger during use by ~70KB per Tile loaded. In practize this should not be an Issue as Apps are restarted frequently.

Additional info can also be found in the commit message directly.

**Comment by opeeters** [comment]
I cannot successfully build: feature/local-leaflet-caching

Error:
```sh
$ ionic serve
> ng run app:serve --host=localhost --port=8100
[ng] Schema validation failed with the following errors:
[ng]   Data path ".builders['app-shell']" should have required property 'class'.

[ERROR] ng has unexpectedly closed (exit code 1).

        The Ionic CLI will exit. Please check any output above for error details.
```

I did a `npm audit fix` and `npm install` (to have `pouchdb` installed).

**Comment by opeeters** [comment]
I was able to build now. A package version related issue it seems..
