### ISSUE TITLE
add sub-index panel to start page & changes map view

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#110]
1) Add sub-index panel to start page. This panel should consist of 4 buttons (cf nearest measuring station panel and above the position of this optional nearest measuring station panel - cf issue #108), belaqi sub-index no2_hmean, o3_hmean, pm10_24hmean and pm25_24hmean. Three of these values are already called for the calculation of the forecast graph. Only the latest value for no2_hmean is missing. The background of the 4 buttons should be the corresponding concentration scale colour. Clicking on one of these buttons should land you in the map-view (with marker "your configured location", no need for nearest station marker). 

2) Two layers need to be added to the map-view: pm10_24hmean and pm25_24hmean. Similar to the description at the top (e.g. text "nitrogen dioxide", etc.), an additional selection ribbon can be added at the bottom of the map view (above "current", "today", etc.), making a selection possible between pm10_hmean (text "hourly mean") and pm10_24hmean (text "running 24-hourly mean"). This text needs to be translatable. For no2_hmean and o3_hmean the translatable text "hourly mean" should be displayed. When selecting the forecast the translatable text "daily mean" should be displayed.

3) To organize the map-view screen more efficiently we propose to remove the layer button on the map and replace it with a search icon. This search button should be the geosearch. The geosearch bar at the bottom can thus be removed.

**Comment by janschulte** [comment]
First Part of this Issue is done with: 19c3133e5cd7b87b3e791de1f4e497108be1b186

**Comment by opeeters** [comment]
part 3: c5f69d7bf825e1f3766e239d3d727ade659a144a
