### ISSUE TITLE
Station data not removed when changing tabs to fast

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#111]
In the map view, when changing tabs faster than station data being loaded, the stations are also not removed when changing yet to another tab. See below:

![screenshot_20190211-131821](https://user-images.githubusercontent.com/323719/52565588-8acf4900-2e07-11e9-8307-164a856020cb.png)

After changing tabs to fast, going back to the  Belaqi tab, in this case the stations of two pollutants are not removed anymore.

**Comment by janschulte** [comment]
Fixed with: 0f4028bf13a70d8c2e7b0fa0ba7031ae3993c765
