### ISSUE TITLE
wrong index in index wheel

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#113]
Rather regularly, the index given in the index wheel does not correspond with both the index at that specific time in the forecast graph and the maximum of the subindices. See here:

![screenshot_20190212-105029](https://user-images.githubusercontent.com/323719/52627045-d7249280-2eb4-11e9-8dad-8af7cbda42f4.png)

checking the index at that time given via the rioifdm:belaqi layer, the value in the index wheel is probably presented wrongly. This is not always the case, but rather frequently.

**Comment by opeeters** [comment]
This is probably cache related. Clearing the cache via the app settings fixes the issue.

**Comment by janschulte** [comment]
Done with: 07b8cbbda511915369d54a15e753218c854124d5

The request for the wheel was still without an timestamp, so after the first request, the wheel gets always the cached result.
