### ISSUE TITLE
Info popup subindex panel opens to low

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#118]
When scrolled to the bottom of the start page slide, the info button of the subindex panel opens awkwardly low:

![screenshot_20190218-002153](https://user-images.githubusercontent.com/323719/52921083-8b8a4280-3313-11e9-9bbe-81cac65c4ae6.png)

It should rather open like this:

![screenshot_20190218-002458](https://user-images.githubusercontent.com/323719/52921104-baa0b400-3313-11e9-86ba-cfa1e3602b44.png)

This is the case when opening the info popup when the slide is not entirely scrolled to the bottom.

**Comment by opeeters** [comment]
present all info pop-ups centrally

**Comment by opeeters** [comment]
this still is an issue, even for the only remaining pop-up in the index-wheel panel. @janschulte can you please look at this.

**Comment by janschulte** [comment]
Done with: a6eb326339cb4a15e5007da52e92b3a5f6d532a2
