### ISSUE TITLE
missing action allow use of location service 

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#121]
On this slide:

![screenshot_20190219-122301](https://user-images.githubusercontent.com/323719/53011674-39473f80-3441-11e9-9521-8915904b543b.png)

The fact that the app does not have permission to use the location is correctly identified, but the message `If you want to make use of the "current position" functionalities, you can activate the location service of your device here.` has no action.

**Comment by opeeters** [comment]
also, when the user has not yet given permission to use the current location and the user activates `current location`, this should trigger the pop-up to allow use of the location service. If permission is not given, the toggle should remain inactive.

**Comment by janschulte** [comment]
Fixed with: 96f66fd69e9302055da3e2924bc66ea0658cfd48
