### ISSUE TITLE
location-header element hiding FAQ-button

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#122]
On the last slide, when scrolled to the bottom of the slide, the FAQ-button is now hidden under the location-header element.

![screenshot_20190219-123225](https://user-images.githubusercontent.com/323719/53012205-9f809200-3442-11e9-85eb-87bc7ba82f05.png)

Maybe add a:
```
.location-header {
	display: none !important;
}
```
only when the last slide is in view?

**Comment by janschulte** [comment]
Fixed with: 0dad6b62b4d7bd68afa4f5ec204927e41a23b1ce and 759243d89993ca31a2709381936109044aa896d0
