### ISSUE TITLE
longer location-header text is not handeled wel

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#123]
Part of the text is hidden:
![screenshot_20190219-124422](https://user-images.githubusercontent.com/323719/53012792-4ca7da00-3444-11e9-9cb6-ab7576e9bc56.png)

![screenshot_20190219-124446](https://user-images.githubusercontent.com/323719/53012797-4fa2ca80-3444-11e9-86d1-0c74145e501c.png)

Maybe dynamically reduce font-size?

**Comment by janschulte** [comment]
Done with: fb42986af914f610c5615a9c0b978416fe88fd76
