### ISSUE TITLE
one time message after upgrade

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#124]
After users install the next update, a pop-up should be displayed, one-time only (first app launch), consisting of a message (still to be determined) and a link to the FAQ-page.

**Comment by janschulte** [comment]
Add this mechanism, which checks at startup if there is installed a new version, then displays the  `update-hint-popover` component as popup. It stores the current version in the app storage, so with a clear cache, the popover will come back on startup.

Added with: 262b0c17191de1a8248ec40087d67fc1550ba5b5
