### ISSUE TITLE
add button to scroll into more forecast

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#131]
Take the trend values (72) from here:
http://www.irceline.be/air/forecast/trend.php

Scroll-button could be a simple arrow to the right..
Maybe also add marker where`tomorrow` starts, or a thin vertical line..

to be refined..

**Comment by opeeters** [comment]
see d9e1d614956c3a6db1ba2b61a4bb366045690b89

Add maximum uncertainty. Let's start with +- 2

**Comment by janschulte** [comment]
Add with: 162f83310076114916bf1d4c2211b2ef3c1a9551
