### ISSUE TITLE
restyle nearest measuring station panel

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#133]
The nearest measuring station panel still needs to be restyled:

<details>
<summary>Mockup:</summary>

![Screenshot_20190323-141325](https://user-images.githubusercontent.com/323719/54866597-1973a600-4d76-11e9-9e74-852f073c603d.png)

</details>

**Comment by SpeckiJ** [comment]
Basic restyling done in https://github.com/irceline/aq-mobile-be/commit/828c2af3ad8478722e7f84e070065080fbd13d13

As of now I completely dropped all information besides the actual index (color) as we did with the other Panels (Short & Long-Term Exposure). I am at the moment  looking into a nice styling for the location information, as I think this is important information in this context, the panel does not really serve any purpose without it. Will update this Issue once there is a implementation ready.

**Comment by opeeters** [comment]
Thanks  @SpeckiJ Maybe display the location data in the "nearest station" marker in the map (after clicking through)?

**Comment by SpeckiJ** [comment]
We tried displaying the data on the map-popup, but that makes it much more cumbersome, as you have to click for every single value and cannot compare any of them (e.g. comparing distances to the nearest stations). JanSch had the idea of using a vertical design, that lends itself more towards the intended use of the panel.

@opeeters :What do you think of this vertical design?

![draft](https://user-images.githubusercontent.com/13851077/54997821-e5de8900-4fcc-11e9-9687-14ee8aecb061.png)

**Comment by opeeters** [comment]
@SpeckiJ Discussed it with the colleagues. Good idea ;-)

**Comment by SpeckiJ** [comment]
Implemented in https://github.com/irceline/aq-mobile-be/commit/d4553cf6631e887a4783e18eab42473a75fd9680
