### ISSUE TITLE
display 24h value in nearest measuring station pane for the PM's

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#134]
For PM10 and PM2.5, in the nearest measuring station panel the 24h mean should be calculated if more than 18 of the last 24 hours is available. If less than 18/24 values are available the next closest station should be selected.

**Comment by opeeters** [comment]
Let's do it differently...
The relevant pm10_24hmean and pm25_24hmean can be taken from `realtime:pm10_24hmean_station` and `realtime:pm25_24hmean_station` via a `getFeatureInfo` request using the lat/long retrieved via the `REST-api`.

On the map page, the `pm10_24hmean_station` and `pm25_24hmean_station` should be added to the the `24hmean` tabs.

**Comment by janschulte** [comment]
I don't find the `realtime:pm10_24hmean_station` and `realtime:pm25_24hmean_station` in http://geo5.irceline.be/rioifdm/wms?service=WMS&request=GetCapabilities&version=1.1.1 or http://geo.irceline.be/rioifdm/wms?service=WMS&request=GetCapabilities&version=1.1.1

Can you give me a hint, where I can find them?

**Comment by opeeters** [comment]
Wrong base URL. You're sending the `getCapabilities` to the `rioifdm` workspace. This should be either `realtime` (to be preferred for speed), or to the general `wms` endpoint (without any workspace sub directory), e.g.:

http://geo.irceline.be/realtime/wms?service=WMS&request=GetCapabilities&version=1.3.0

**Comment by janschulte** [comment]
Added station layer to map with: 81115df9b6af487af0713a40049f2712a16db075
