### ISSUE TITLE
Message location service of device is deactivated

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#135]
When having no locations configured and you activate the "current location" in the app, the app correctly asks for permission to use the location service of the device if this permission has not been granted before, but, no message is displayed to activate the location service of the device when location service is inactive.

If possible, the location service should be activated automatically when prompted for permission to use the service. In all other cases:
1) BelAir has permission to use location service, but the location service is inactive and user activates "Current location"
2) BelAir has permission to use location service, but the location service is inactive and user has activated "Current location" previously and returns to the app

At least a message should be added pointing out that the location service is inactive and requires a user intervention, but best, a pop-up with a button to active the service directly..

**Comment by opeeters** [comment]
also see #145 in this context

**Comment by janschulte** [comment]
It should work now in general for iOS and Android. For iOS we have the OS restriction, that the app can't request the permission multiple times. So, when the user decides to denied the location permission, the only option is to reset this permissions in the settings of the OS. We add a check if the permissions are denied and give the user the hint, that the permission have to set in the settings.

Adjustments was made with: e558ad67288a141c9fc75b54e64b44e1ad689871

**Comment by janschulte** [comment]
See here for more information the ios section: https://github.com/dpa99c/cordova-diagnostic-plugin#requestlocationauthorization
