### ISSUE TITLE
White screen after installing production release

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#137]
See internal release 0.8.0. in the Google Play Store
On Android 7.0 (Galaxy S6) all is well

On Android 8.0.0. (Galaxy A5), on launching the app you only get a white screen (also after removing all data from previous install).

**Comment by opeeters** [comment]
Same problem on Android 7.0 (Galaxy A5). A bit bizarre since Android 7.0 (Galaxy S6) is fine..

**Comment by janschulte** [comment]
Fixed with: 369c1b3c0e62e11528b9e4882de1e1ca1ad2bace
