### ISSUE TITLE
zoom map page

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#139]
Going to the map page via the navigation at the bottom of the app some times gives bizar results:

![Screenshot_20190327-112513](https://user-images.githubusercontent.com/323719/55069014-6233a380-5083-11e9-8cbc-058c187ee477.png)

add default zoom?

**Comment by janschulte** [comment]
Adjusted with: d58b97cf4c23524f0c4b60151671b36d78c78a7c

**Comment by opeeters** [comment]
reviewing d58b97c
@janschulte 
Does this mean we might have the same problem again should our servers be slower to respond (e.g. during high work load senario's)?

**Comment by janschulte** [comment]
@Olav This is just an internal initialization of the map component. So slower responses will not have an effect on that.
