### ISSUE TITLE
no forcast graph when one of the 3 trends is missing

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#140]
When one of the 3 trends from http://www.irceline.be/air/forecast/trend.php is missing, no graph is shown. If at least one of the three trends is present, a forecast can be based on the in app no2 trend plus one (or two) from the trend.php.

**Comment by janschulte** [comment]
Adjusted with: aaaac13a7b51ab60f60ed430584f782366c6b199

**Comment by opeeters** [comment]
still need to test.. will close this as soon as I get to it

**Comment by opeeters** [comment]
We still need to add a telling message for the case that `https://www.irceline.be/air/forecast/trend.php` is unavailable.

**Comment by janschulte** [comment]
Ist the `trend.php` is not reachable the following screen should appear now: 
![](https://user-images.githubusercontent.com/3830314/56209140-16a56180-6053-11e9-8440-5fb22996a6ce.png)

Done with: c47d6d0e9467499535aa7f9518131651cc089601
