### ISSUE TITLE
Restyle Map Page

### ISSUE THREAD

**Issue by SpeckiJ** [irceline/aq-mobile-be#142]
The Map page needs to be restyled to match the new design.

A first mockup of the new design with sliders is implemented here: https://github.com/SpeckiJ/aq-mobile-be/tree/feature/ionic4-dev Any opinions @opeeters @janschulte ?

Currently the Slider for the hourly/daily/yearly selection disappears when its not available. This can of course be changed.

Mockups:

![mapRedesign](https://user-images.githubusercontent.com/13851077/55169415-08aba180-5175-11e9-9d07-0211be6d5bbe.png)

![mapRedesign2](https://user-images.githubusercontent.com/13851077/55169491-2bd65100-5175-11e9-9ec6-83e92ea9f2c1.png)

TODO:

Actually use correct colors in the top phenomenon bar.

**Comment by opeeters** [comment]
@SpeckiJ 
I like it. 
But actually, I was thinking along the lines of using the ionic range slider and depending on the pollutant/index do this:
- number of steps = the number of temporal aggregations
- have only one slider
- change a title above the slider when depending on the slider position (than we have enough space for a more descriptive title, e.g. "annual mean (long term exposure)" etc. )

The following order of the steps (from left to right):
- anmean (not for BelAQI)
- hmean
- 24hmean (not for belaqi, bc, no2 and o3)
- dmean forecast today <> +3 days (not for bc)

**Comment by SpeckiJ** [comment]
Okay I think I now get the idea.

Short followup-question: 

Shall the labels for the different positions (amean, hmean, current, today, tomorrow, +2days) disappear completely and be replaced by the single descriptive title, or shall they move under the slider while the descriptive title moves above the slider?

**Comment by opeeters** [comment]
I thought that a labels could disappear completely. But if you think there would still be space below the slider for labels, that would maybe be a nice touch so that users see what is available.. Maybe with a lighter font color?

**Comment by SpeckiJ** [comment]
First draft (legend, no additional labels)

<details>
<summary>(legend, no additional labels)</summary>

![mockup_v2](https://user-images.githubusercontent.com/13851077/55235616-40c2eb00-522e-11e9-97f0-84aab5f21e3d.png)
</details>

<details>
<summary>(legend, with additional labels)</summary>

TBD

</details>

**Comment by opeeters** [comment]
@SpeckiJ Looks good.
You could maybe make a:
```
<table>
<tr>
<td>
{{the slider}}
</td>
</tr>
<tr>
# <td>'s = # of aggregations, where width of every <td> = 100% / # of aggregations
<tr>
</table>
```

**Comment by SpeckiJ** [comment]
As of https://github.com/irceline/aq-mobile-be/commit/1d46e65c7409f03d61745c567d3cd1f2a9e618cf most of the styling is now production-ready (To be tested on iOS - will update).

TODO:

- [ ] Test on iOS devices
- [ ] Style sliders
- [ ] Replace placeholder legends with correct ones

@opeeters: For the 0.9 milestone, shall we adopt the single slider for all steps or the 2 seperate sliders?

**Comment by opeeters** [comment]
If feasible, it would be great to have it on one slider already.
I can add the text message under the legend if this helps.
Can you fix the font of the legend, please?

**Comment by opeeters** [comment]
iOS seems fine so far

**Comment by SpeckiJ** [comment]
The Slider for Layer Selection is implemented as of https://github.com/irceline/aq-mobile-be/commit/ee5733d1a61c0090d66258f021fa17354b5c10f6.

Currently the descriptions for the different languages are still missing (see for example english here:) https://github.com/irceline/aq-mobile-be/blob/ee5733d1a61c0090d66258f021fa17354b5c10f6/src/assets/i18n/en.json#L261

@opeeters I think it would be easiest if you add the legend-labels yourself, the template is already copied over into all languages.

TODO

- [ ] Replace placeholder legends with correct ones
- [ ] Add translations

**Comment by opeeters** [comment]
translations added with eee359a

**Comment by opeeters** [comment]
@SpeckiJ 
Please also make sure users enter into the right time aggregation. 

For instance, entering the map-page via the `short-term exposure` buttons should open the map page in `hmean` for `belaqi`, `no2` and `o3` and `24hmean` for `pm10` and `pm25`.

Entering the map-page via the `long-term exposure` buttons should open the map page in `anmean`.

**Comment by SpeckiJ** [comment]
As the Map View is now localized, the whole navigation between the "wheelview" and "mapview" has to be revamped.

Will do so asap tomorrow morning :+1:

**Comment by opeeters** [comment]
also, the legends need to be changed correctly on time aggregation change anmean>hmean>24hmean>dmean etc.
Can be verified now that legends are all there with abc2ff90910a8338277dc9bb9e818152839529b8
24hmean = dmean

**Comment by SpeckiJ** [comment]
Okay I have implemented the changes in https://github.com/SpeckiJ/aq-mobile-be/commit/b15f22cccd3c94197709ab7fd503c968d543ed78

The Mockups for the Map View all feature colored borders in the pane for phenomenon selection above the map (similar to the panels on the WheelView). As we have several different panels, it is currently unclear where these colors come from (short-term vs. long term vs. nearest-station). @opeeters Do you have any idea?

For the time being (the 0.9 release) I would propose just coloring them all the same color (gray), implementing the correct border color in the 1.0 release.

**Comment by opeeters** [comment]
@SpeckiJ 
Fine by me to move implementation of colors to 1.0. But please transfer the above changes to this repo..

Normally all (or nearly all) values needed to color the borders should already be in the cache by the time a user gets to the map page.

The short-term:
hmean and/or 24hmean
Long term:
anmean

The forecast tabs:
new `getFeatureInfo` requests would be needed..

**Comment by opeeters** [comment]
No new `getFeatureInfo` are necessary for the time being. Only `BelAQI` sub-index tabs get color.
This means the following tabs:
- BelAQI hmean
- NO2 & O3 hmean
- PM10 & PM2.5 24hmean

This data can be read from cache.

**Comment by SpeckiJ** [comment]
This should be implemented as of https://github.com/irceline/aq-mobile-be/commit/cc1e930ef6cadbe5e09d5a2699d4213ea66e7a39. 

@opeeters Can you confirm this works as intended?

**Comment by opeeters** [comment]
Looks good!

One issue though. Switcing to the map page (either via navigation or the short-term exposure panel) should land you in `belaqi-mode`, meaning that the AQI, NO2, O3, PM10 (24hmean) and PM2.5 (24hmean) have a coloured icon.

Currently this only works as intended when going via the pm10 & pm2.5 buttons of the short-term exposure panel.

**Comment by SpeckiJ** [comment]
This should hopefully be implemented correctly as of https://github.com/irceline/aq-mobile-be/commit/083753013025472c819f95009c1c4f08fbf7306d

**Comment by opeeters** [comment]
Still not working as intended. Only the two PM-buttons in the short-term exposure panel work correctly.

When going via the global navigation to the map-page you land by default in hmean-mode. When going via O3 and NO2 in the short-term exposure panel as well.

Additionally, in this example:

![Screenshot_20190502-224132](https://user-images.githubusercontent.com/323719/57108657-bb9e8a80-6d33-11e9-8935-f9bde8b0635b.png)

![Screenshot_20190502-224142](https://user-images.githubusercontent.com/323719/57108671-c0633e80-6d33-11e9-8493-f0f6b960e378.png)

see how the colour of the PM's and O3/NO2 seems to be switched..

**Comment by SpeckiJ** [comment]
I have changed the behaviour of the map panel to now always set belaqi-mode when navigating to the map via the short-term panel. 

Just to clarify a short question: 

> When going via the global navigation to the map-page you land by default in hmean-mode

This is the correct and intended behaviour right?

**Comment by opeeters** [comment]
No, I was describing the unintended behavior there. Going via the global navigation should land you in belaqi-mode to.

**Comment by SpeckiJ** [comment]
Okay this might explain my confusion. I have now changed the default mode in https://github.com/irceline/aq-mobile-be/commit/2d8597821c65eff50c21b70fe60b1178830b927d and https://github.com/irceline/aq-mobile-be/commit/8e284f2d78de93f79b011800223b6f34cfd67a09.

The App is now in belaqi by default, and only enters hmean-mode if the PM10 or PM25 Slider is manually set to hmean.
When navigating via the short-term panels the mode is also forcefully set to belaqi-mode.
