### ISSUE TITLE
`use current location` button 

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#145]
When clicking `use current location`:
![Screenshot_20190331-224302](https://user-images.githubusercontent.com/323719/55294825-c7cabb80-5406-11e9-989f-cc7ac0132181.png)

In both the introduction slides and when going to the model from any of the `create new location` buttons in the app. When testing via `ionic serve --lab`, all is well. This only doesn't work in a compiled app, both `Android` and `iOS`.

XCode error message:
```
ERROR: Code: undefined, Message undefined
```

**Comment by janschulte** [comment]
This is also be fixed with: e558ad67288a141c9fc75b54e64b44e1ad689871

**Comment by opeeters** [comment]
On iOS (on a device - iPhone 6), I get the following error:

```
ERROR: Error while gathering location: plugin_not_installed
```

**Comment by SpeckiJ** [comment]
Hm this seems weird.

To further debug the issue I have 2 questions:

- What iOS Version are you running on the device?
- How are you transferring the App to the device? (e.g. limited store release, xcode, etc.)

As the diagnostics plugin is native to the platforms, it is not installed in some development scenarios (e.g. ionic view in the browser). Do you think the issue might stem from that?

**Comment by opeeters** [comment]
The button also fails with a `debug.apk` on Android (Android 7, Galaxy S6)

**Comment by opeeters** [comment]
On iOS:
- transfer via Xcode (10.2)
- iPhone 6 and 12.1.4 (not yet the dreaded 12.2, but there will still be users with an older iOS version)

**Comment by opeeters** [comment]
OK, this might be a false alarm. I did a clean clone of the repo and now it's working on iPhone at least.. I'll continue testing...
