### ISSUE TITLE
preparing BelAir for GeoServer update

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#147]
Using `geo5.irceline.be` as endpoint instead of `geo.irceline.be`, the `GetFeatureInfo` request returns, e.g.:

```json
{

    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "id": "",
            "geometry": null,
            "properties": {
                "GRAY_INDEX": 37.42167663574219
            }
        }
    ],
    "totalFeatures": "unknown",
    "numberReturned": 1,
    "timeStamp": "2019-03-31T21:37:52.830Z",
    "crs": null

}
```

Instead of (as with `geo.irceline.be`):

```json
{

    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "id": "",
            "geometry": null,
            "properties": {
                "GRAY_INDEX": 37.42167663574219
            }
        }
    ]

}
```

Most of the `GetFeatureInfo` input is not consumable anymore with the new `json` format which only adds info. BelAir needs to be prepared for a period where both formats need to be successfully consumed.

**Comment by janschulte** [comment]
I checked all services, with the new `geo5.irceline.be` url and this work good so far. I only recognised, the server don't deliver in https.

Commit 1877555c7aa6784b9f00165ab62bb1cf26cb47c3 adjusted all urls.

**Comment by opeeters** [comment]
Ah, OK, how sloppy of me. Indeed, `geo5` did not get `https` yet..
Let's keep developing against `geo5` for the time being...
