### ISSUE TITLE
implement user locations slides on the map-page

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#148]
In line with the start page, the map page should also be user location specific. Keep panning activated in the map, but make sure that at least the location label is swipeable.

**Comment by SpeckiJ** [comment]
The core restructuring of the Map View is done in https://github.com/SpeckiJ/aq-mobile-be/commit/4394c96c57acd72139e7cc6cc421e247a63d5a24. (Currently not merged into "master" as it is not production-ready.
As having multiple Map Views was not considered during initial development, large parts had to be restructured. 

TODO:

- [ ] restore Legend
- [ ] improve navigation between different views
- [ ] add colors to phenomenon navigation bar
- [ ] bugfixes & stability

**Comment by SpeckiJ** [comment]
This should all be done via https://github.com/irceline/aq-mobile-be/commit/ce6ca390bcbd33e554e0918d950ca1c68995f76f

**Comment by opeeters** [comment]
@SpeckiJ 
I often empty maps and/or wrong time aggregation. E.g. here I should have gone to no2_hmean, but I end up in a hybrid state with the text of anmean, the slider in the right position, but no map:

![Screenshot_20190404-181349](https://user-images.githubusercontent.com/323719/55571392-b8e55100-5705-11e9-9335-0f34691c5a22.png)

I did do a `npm install`...

**Comment by SpeckiJ** [comment]
I will further debug the issue - Angular sometimes does not refresh the view (for some wierd reason). If you change into Landscape mode and back suddenly everything is fine. 

Will update this Issue once this is all sorted out.

**Comment by opeeters** [comment]
@SpeckiJ 
problem not yet solved with 7c30effb9ad36850c572bad35c47f470450ec1bf
The legends seem to change correctly, but somethings seems to be blocked (in debug apk on Android 7 at least).

**Comment by SpeckiJ** [comment]
With https://github.com/irceline/aq-mobile-be/commit/7c30effb9ad36850c572bad35c47f470450ec1bf (fix invisible elements upon first loading) and https://github.com/irceline/aq-mobile-be/commit/a1f03cb0f605861c4e28246acc234937579c7578 (fix grey map) some issues are fixed now. 

Will test if any other issues pop up.

**Comment by opeeters** [comment]
a1f03cb0f605861c4e28246acc234937579c7578 seems to solve it. This is going into an internal test..

**Comment by SpeckiJ** [comment]
fixed navigation from short-term panels according to https://github.com/irceline/aq-mobile-be/issues/142#issuecomment-479478721 with https://github.com/irceline/aq-mobile-be/commit/f056d2bc9462f5182b0e98baf91b2a7701bd7007

fixed view not updating on language change https://github.com/irceline/aq-mobile-be/commit/b200b523e9ab1b98f8b2505af4f3b7d23aa58892

The Map view now seems to be pretty stable.

**Comment by opeeters** [comment]
agree ;-)
