### ISSUE TITLE
resuscitate diagram page

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#149]
New version of diagram page should have:

1) One diagram per timeseries (closest measuring station per user location - slides cf start/map page)
2) For timeseries which are part of the BelAQI (no2_hmean, o3_hmean, pm25_24hmean, pm10_24hmean), the value dots should have the colour of the corresponding sub-index. Other time series should be grey
3) default the following timeseries:
 - no2_hmean
 - o3_hmean
 - in app calculated pm25_24hmean (with tab under diagram to pm25_hmean)
 - in app calculated pm10_24hmean (with tab under diagram to pm10_hmean)
 - bc_hmean
4) functionality to add other timeseries

**Comment by janschulte** [comment]
Currently there are some questions to this new diagram view:
- Which timeframe should the diagrams show by default (today & tomorrow)
- Should the timeframes be adjustable by the user?
- How should the `pm24_hmean` and `pm10_24hmean` be calculated?

**Comment by opeeters** [comment]
* default `today & yesterday` is fine. 
* for the time being no user adjustable timeframes, just ability to scroll through time by pulling series left or right
* the `24hmean`'s (`pm25_24hmean` and `pm10_24hmean`) should be calculated

**Comment by janschulte** [comment]
How should I handle measuring gaps while calculate the 24h mean?

**Comment by opeeters** [comment]
For a valid 24hmean you need 75% of the data, in other words 18 of the 24 hourly values.

**Comment by opeeters** [comment]
Labels x-axis overlap on smaller screens:

![Screenshot_20190430-105110](https://user-images.githubusercontent.com/323719/56951172-6b5ad900-6b37-11e9-9484-ba16d53cb4c0.png)

Maybe have date below time?
