### ISSUE TITLE
add GA

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#150]
Add GA:
https://ionicframework.com/docs/native/google-analytics

I will add tracker id.

I will change `getFeatureInfo` back to `https` for GDPR compliance. Any other GDPR issues I might be overlooking?

**Comment by opeeters** [comment]
adding cordova-plugin-firebase-analytics leads to iOS build error:

```
ld: library not found for -lFirebaseCore
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by janschulte** [comment]
Works now by using a new plugin `cordova-plugin-firebase`. Done with: 8f1dde93669ace7863b0e7aa126370420f951515 and 5446f2aa09f5075b6e06e6e4bc3bdcff61284a90
