### ISSUE TITLE
positioning `getFeatureInfo` request

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#151]
Take this location as example:
Koningin Astridlaan 129, Mechelen

On the start page this location receives an NO2 subindex of 5 where this location is in an index 9 location.

![Screenshot_20190402-141522](https://user-images.githubusercontent.com/323719/55402163-0b324080-5553-11e9-9945-eaa8b181f0d0.png)

On the other side of this ring road, e.g.:
Koningin Astridlaan 140, Mechelen

On the start page this location receives an NO2 subindex of 9 where this location is in an index 5 location.

Something is wrong with the location as inputted into the `getFeatureInfo`.

**Comment by opeeters** [comment]
revise `calculateRequestBbox` in `src/app/services/value-provider.ts`

**Comment by opeeters** [comment]
@janschulte 
Please revise bdec01a57c1805ec4cf314bf4c3a6c04eb48c080

**Comment by janschulte** [comment]
@Olav, yes looks also as a valid approach. No objections.
