### ISSUE TITLE
fix some links start page to map page

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#153]
The following links go wrong:
short-term exposure
- no2 lands in no2_anmean -> should be no2_hmean
- pm10 lands in pm10_anmean -> should be pm10_24hmean
- pm25 lands in pm25_anmean - >should be pm25_24hmean

**Comment by SpeckiJ** [comment]
I have fixed the above mappings.

Short Question @opeeters: Where shall the "nearest-station-panel" link to? Annual or Daily Means?

**Comment by opeeters** [comment]
Have changes been commited?
In answer to your question:
cf  #134
bc, no2, o3 -> hmean
pm10 and pm25 -> get color based om result `getFeatureInfo` and go to 24hmean (with 24hmean_station layers added)
