### ISSUE TITLE
add in app message when "expiration" of push-notification is still valid

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#155]
The push-notifications are send with a:
```json
  "data": {
    "title": "High pollution",
    "body": "patatie patata",
    "topic": "brussels",
    "expiration": "2019-04-09T13:00:00+02:00"
  }
```
When `data.expiration` has not yet passed, above the index wheel an in app warning should be displayed (cf mock-up) with `data.title`. When clicked, a pop-up should appear with all the elements of `data`.

**Comment by opeeters** [comment]
The pop-up should have following elements:
```
Message is valid until: {{data.expiration}}
For your notification channel:  {{data.topic}} (might be multiple)
{{data.title}}
{{data.body}}
```
The language in the pop-up should correspond to the language set for the app.

Users with language set to NL, they get `brussels_nl` automatically and should thus receive `flanders` and `brussels_nl`. If they also follow `wallonia`, this is just indicated in `For your notification channel:  {{data.topic}}`. All other elements are NL. Same goes for the case that the app is set to FR (but than with `brussels_fr`, etc. If a user has the app set to e.g. FR and only follow `flanders`, the language in the pop-up will be NL though. Same goes for the case that the app is set to NL and only `wallonia` is followed.

Users with language set to EN and DE, if they only follow `flanders` or `wallonia`, they only get either NL or FR accordingly. If the user follows  `flanders` and `brussels` and/or `wallonia`, they get both NL and FR, e.g. like so:

```
Message is valid until: {{data.expiration}}
For your notification channel:  {{data.topic}} (might be multiple)
{{data.title_nl}}
(There is a french version below)
{{data.body_nl}}
{{data.title_fr}}
{{data.body_fr}}
```

**Comment by janschulte** [comment]
First version is done with: 8a41cf67282345f95b0399fa363a0c5035a3fb3a

Currently the aggregation handling with brussel_fr and brussel_nl is missing. Will be done tomorrow.

**Comment by janschulte** [comment]
With 183a0dd8218b832301ef8eec79d8b8c5a17bdce2 the last point is also implemented.
I updated the `readme.me` and adjusted the notification section with a new sample notification. Please be aware that all properties are also set in the `data`-object. These properties are used internally.
