### ISSUE TITLE
fix hardware back button on Android with Ionic 4

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#159]
With `Ionic 4` the hardware back button misbehaves on Android.

The partial fix (see ef57e83f702f2af0bff5a6ba4939c0266e63046c) is based on this discussion:
https://forum.ionicframework.com/t/hardware-back-button-with-ionic-4/137905/44

In this part still needs some attention:

```
        this.routerOutlets.forEach((outlet: IonRouterOutlet) => {
            if (this.router.url === '/tabs/start') {
                navigator['app'].exitApp();
            } else {
                window.history.back();
            }
        });
```
The case when the user is on the start page, but opens either the settings or the information overlay needs to be detected, closing settings and overlay instead of exiting the app.

**Comment by opeeters** [comment]
@janschulte Please review commit ef57e83

**Comment by SpeckiJ** [comment]
@opeeters I have refined the behaviour of the back button to first close any open modals before exiting the App in https://github.com/irceline/aq-mobile-be/commit/b5d89613271e8804268c57c25e397a50bec35d4e. Can you test whether this is now the desired behaviour?

**Comment by opeeters** [comment]
@SpeckiJ For the modals this works perfectly.

We still need a fix for the overlay (overlay-info-drawer). Maybe check for `DrawerState`=`open`?

**Comment by SpeckiJ** [comment]
Unfortunately to enable the Drawer to be closed by the back-button large refactorings had to take place (Drawer State was only stored locally and therefore unaccessible by the general app especially the backButtonListener).

Should be done with https://github.com/irceline/aq-mobile-be/commit/1e05af5a123e4914f88257afc83a5e52ee740f19. On Android it seems to work fine, iOS is not tested.
