### ISSUE TITLE
Error message case when no new data is available for more than 2 hours

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#162]
When there is some interruption in the realtime chain and the last available data is older than e.g. 2 hours a subtle error message (e.g. just under the last update timestamp) should be displayed:

The last update is older than normal due to a technical issue. We are doing our best to repair the issue as soon as possible.

Probably it will be best to add a `current_time` value to http://www.irceline.be/air/time_app_json.php ?

**Comment by SpeckiJ** [comment]
I have added the message with https://github.com/irceline/aq-mobile-be/commit/cca72d5ed8ac5f2a652bbc1b857deb8081e08369. The length of the text should be somewhat consistent across all languages as there is not enough room for many more words in the header.

Not tested on iOS yet!


Currently the translations are missing for nl, de and fr:

https://github.com/irceline/aq-mobile-be/blob/cca72d5ed8ac5f2a652bbc1b857deb8081e08369/src/assets/i18n/nl.json#L175

https://github.com/irceline/aq-mobile-be/blob/cca72d5ed8ac5f2a652bbc1b857deb8081e08369/src/assets/i18n/de.json#L175

https://github.com/irceline/aq-mobile-be/blob/cca72d5ed8ac5f2a652bbc1b857deb8081e08369/src/assets/i18n/fr.json#L175

**Comment by opeeters** [comment]
There probably is a more elegant method to determine <ion-row> height based on content, but 81d4d1f is enough for `1.0`. Let's look at this for `1.1`.

**Comment by SpeckiJ** [comment]
Header size is now set automatically by the framework as of https://github.com/irceline/aq-mobile-be/commit/a62751f39b7ae9ccb97b09e7cccb18771c1eecb8
