### ISSUE TITLE
bug tooltip forecast graph

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#164]
The tooltip in the forecast graph is displayed threefold:

<img width="361" alt="Screenshot 2019-05-02 at 14 41 26" src="https://user-images.githubusercontent.com/323719/57075900-7f920800-6ce8-11e9-8856-32e71753184b.png">

**Comment by SpeckiJ** [comment]
The graph view in general seems to be bugged occasionally. See attached Screenshot (tried to also show location so the bottom is cropped):

<details>
<summary>Screenshot</summary>

![WhatsApp Image 2019-05-02 at 14 44 20](https://user-images.githubusercontent.com/13851077/57076050-e7485300-6ce8-11e9-931e-950a468f6d0f.jpeg)

</details>

**Comment by opeeters** [comment]
Also, changing back to start-page often results in:
![Screenshot_20190502-151531](https://user-images.githubusercontent.com/323719/57078002-ad2d8000-6ced-11e9-93cd-91d2f6d4750a.png)

Line color is incorrect. To reproduce, turn phone to landscape and back to portrait.

**Comment by janschulte** [comment]
The tooltip issue and the wrong colored line is fixed with: 915f520193aeaf4c3ff113246721c9ceb3feca65
