### ISSUE TITLE
bug adding additional user location

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#165]
It is not possible to add an additional user location.

Steps to reproduce:
- add location (e.g. Mechelen)
- add second location (e.g. Leuven)

When you try to add second location, the lat/long of the first location is taken and the location name is populated with the name of the first location:

![Screenshot_20190502-151705](https://user-images.githubusercontent.com/323719/57078413-8cb1f580-6cee-11e9-8551-4338d040d8e2.png)

It is possible to manually drag the location icon to the location you intended and change the name, but this is not very user friendly.

**Comment by SpeckiJ** [comment]
Unfortunately i cannot recreate the error.

The only way I can get to the screenshot above is by not clicking the "search" button on the bottom right of the on-screen keyboard, but by pressing the "back" button on my phone (This way i never actually search for the location, just enter it into the textfield and then close the keyboard.)

This could be prevented by clearing the screen (e.g. the old location data) after the keyboard is opened, but I am not sure whether this is really the issue described above.

**Comment by opeeters** [comment]
Same issue though in the browser version (via `ionic serve`).

**Comment by opeeters** [comment]
With the second search, the map goes to the location of the first stored user location. The location name is populated with the name of the first location (and not with the searched name as it should).

**Comment by opeeters** [comment]
doing a `clear cache` in between first and second search solves the issue.

**Comment by SpeckiJ** [comment]
As of https://github.com/irceline/aq-mobile-be/commit/e561e6037f43fdcdf5b8e614e2fd7e5213e0dceb the app is now closing the Modal once a location has successfully been added.

I like this interaction much more as it clearly shows that the location has been added, as it now visually appears in the list that is shown once the modal closes. Previously you could easily miss the Location being added, as the Toast "Location has been successfully added" is only shown very shortly and in an uncommon position (showing info via a toast is very uncommon inside the app).

If the user wants to add multiple locations, the "Create new Location" button has to be clicked multiple times. As this is not an interaction that is done often (ideally only once or twice), I think the benefit from clearly signalling once a location has been added overweighs this small "drawback" of the user having to do one more button click and reopen the menu.

@opeeters Any Opinions?

**Comment by opeeters** [comment]
This is indeed much better behaviour. But I still have the same issue with adding additional user location, both in the browser version and on a device (Samsung S6, Android 7). I also tried different installs (unsigned and signed via Play Store). 
Did you update packages cf a5a21d49b187ecb30dcd7b432736d41a938c8c48?
Maybe the one or other package upgrade is not compatible with the rest?

**Comment by opeeters** [comment]
Also, to reproduce, I think you need to close the app in between adding the first and the second location

**Comment by janschulte** [comment]
Fixed with: 451c981454f698f6f46c0c4df1025dedaa27f6aa

This was indeed a result of the updated packages. Some behavior to create the caching key for the nominatim request changes.

**Comment by opeeters** [comment]
OK, thanks!
