### ISSUE TITLE
With every build the .apk size increases

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#169]
This is an overview of the .apk size of recent releases, up to the last public release using ionic v3:

| - release -  | size (MB) |
| :-------------: |-------------:| 
| 0.9.5 | 21,0 |
| 0.9.4 | 19,5 |
| 0.9.3 | 19,0 |
| 0.9.2 | 18,5 |
| 0.9.1 | 17,6 |
| 0.9.0 | 17,1 |
| 0.8.9 | 15,7 |
| 0.8.8 | 15,3 |
| 0.8.7 | 14,3 |
| 0.8.6 | 13,7 |
| 0.8.5 | 13,2 |
| 0.8.4 | 9,15 |
| 0.8.3 | 9,13 |
| 0.8.2 | 13,1 |
| 0.8.1 | 11,8 |
| 0.8.0 | 19,1 |
| 0.7.1 | 6,27| 

`0.7.1` was still with ionic v3 (last public release).

The size seems to become a bit bloated..

**Comment by SpeckiJ** [comment]
I have cloned the Repository into a fresh directory and get the following result upon first building with:
`ionic cordova compile android --verbose --release`

| - version -  | size (release)(MB)|size (release)(MB)|
| :-------------: |-------------:| -------------:|
| 0.9.5 | 13,6 | 15,7|


I have looked into the apk (using Android Studio) and it does not seem that we have issues with our code (e.g. generating more icons than necessary etc.). See also the attached Screenshot for space usage:

![apksize](https://user-images.githubusercontent.com/13851077/57462684-9f41a700-7279-11e9-9b98-de262dac0390.png)

The sizes also seem to be reasonable:
The /assets/www folder has all of the javascript code
The /lib folder has sqlite drivers for 5 different Processor architectures (arm, x86, etc.)
The classes.dex contains all the Java Code

**Comment by SpeckiJ** [comment]
This is a screenshot of inflated apk.

![aqmobile](https://user-images.githubusercontent.com/13851077/57930709-f9b0b800-78b6-11e9-8c8f-6ee49d6c18aa.png)

You can clearly see that Cordova has compiled a lot of old versions of our source files into the app. When preparing the App via `ionic cordova prepare android` the complete `www/` folder is copied into the `platforms/android/...` directory. This also includes a multitude of old cached versions generated by ionic during development.

Unfortunately I could not find a way to force ionic to clear the cache prior to preparing/building the app (see also [here](https://stackoverflow.com/questions/32197369/how-to-force-refresh-the-cached-source-files-upon-ionic-build-run), so I am now manually deleting the directories.

I have added a hook in https://github.com/irceline/aq-mobile-be/commit/848425248953a97e7ab6fd11a04bdecbbcca26d1 that clears the old files. @opeeters you need to rerun `ionic cordova prepare android` or `ionic cordova build android` for the changes to take effect. I theory you should then be able to reproduce the apk sizes from my last comment

**Comment by opeeters** [comment]
Seems to do the trick. Thanks @SpeckiJ
