### ISSUE TITLE
fragmented map

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#171]
This still happens regularly:

![Screenshot_20190515-011035](https://user-images.githubusercontent.com/323719/57920187-be07f500-789a-11e9-88a4-d2241ff91987.png)

Both the OSM and WMS-overlay are not fully loaded on the canvas. Moving the map (up) loads the additional tiles.

**Comment by SpeckiJ** [comment]
Unfortunately this race condition is really hard to reproduce. I have not been able to reproduce with https://github.com/irceline/aq-mobile-be/commit/73fe461151cb4fe9eb4c5e3f27e611311ef7c089, but i may have just gotten lucky.

@opeeters Can you check if you can reproduce it?

**Comment by opeeters** [comment]
This seems to solve the issue in multiple situations on first load (booting app > going to map page).

There still is the following problem:
- add multiple locations
- put BelAir in background, e.g. by going to another app

Result:
The first map slide you go to is fine, but when you slide to other locations, the map is fragmented.

Is the map somehow being loaded differently in this case?

**Comment by SpeckiJ** [comment]
Indeed the map is instantiated differently when first loading, and I could reproduce the error when having multiple locations.

This should be fixed in https://github.com/irceline/aq-mobile-be/commit/3a5afd9563ef31273b6f2d210271f902c48c6370.

**Comment by opeeters** [comment]
Seems OK now
