### ISSUE TITLE
permission use location service needed to display maps

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#172]
When the use of the location service has not been permitted (e.g. installing the app and manually configuring locations), no map is shown for the configured locations when switching to the map page:

![Screenshot_20190521-213126](https://user-images.githubusercontent.com/323719/58125576-2f380700-7c11-11e9-9807-a0ed526ab09a.png)

It should be possible to consult maps for manually configured locations even if the permission to use the location service has not been granted.

**Comment by SpeckiJ** [comment]
This should hopefully be fixed with: https://github.com/irceline/aq-mobile-be/commit/75efc631fb2af1a37a37180c4a962614e5716830. This is still untested!

@janschulte Can you please test this on an actual Phone?

**Comment by opeeters** [comment]
All is well on the phone I tested this on.
