### ISSUE TITLE
improve notifications location service status

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#173]
When the app was granted permission to use the location service of the device, but the location service of the device has been deactivated, and the "current location" option in the app has been activated, there is nothing being displayed (or only the locations which have previously been configured). 

![Screenshot_20190521-222040](https://user-images.githubusercontent.com/323719/58128130-36621380-7c17-11e9-9c21-eb6d3b868e22.png)

There should be a message (cf ionic 3 version of the app), pointing to the fact that the location service of the app has been deactivated, also in the case that there are other configured locations present. 

Maybe use the current location slide for this, just add a centrally placed message, e.g. the `network.geolocationDisabled` and `network.geolocationDisabledExplanation` messages.

Should there be configured locations present, maybe add a message "swipe this screen to the left to consult data for the previously configured locations".

**Comment by SpeckiJ** [comment]
If Location Permission has not been granted or the location feature of the device has been turned off, the location is ignored in all views, as they are based on the views returned by `getVisibleUserLocations()`.


This function filters and checks `this.locationModeAllows()` when returning the current location, not returning it when the device location is not available.

https://github.com/irceline/aq-mobile-be/blob/75efc631fb2af1a37a37180c4a962614e5716830/src/app/services/user-location-list/user-location-list.service.ts#L104

To fix this issue `this.locationModeAllows()` may need to be split into seperate functions, or a new function is introduced that is called by the view and checks for this specific case (location permission allowed but gps turned off and current location on).

**Comment by SpeckiJ** [comment]
I have refactored the handling of geolocation errors (permission denied, location unavailable) in https://github.com/irceline/aq-mobile-be/commit/765eaaebb65c201ddca52257b00e899ba40cdc9a

**Comment by opeeters** [comment]
seem OK now
