### ISSUE TITLE
add legend under every graph (graph-page)

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#174]
A little explanation under every graph, either "hourly mean" or "hourly mean (grey) and 24-hour running mean (BelAQI-colors)", depending on the pollutant.

**Comment by SpeckiJ** [comment]
I have added the Labels in https://github.com/irceline/aq-mobile-be/commit/0e3cab70dd17a56452ee7c9f6a46e6876d6e2c77.

@opeeters This requires some new translations:

https://github.com/irceline/aq-mobile-be/blob/0e3cab70dd17a56452ee7c9f6a46e6876d6e2c77/src/assets/i18n/nl.json#L118


https://github.com/irceline/aq-mobile-be/blob/0e3cab70dd17a56452ee7c9f6a46e6876d6e2c77/src/assets/i18n/de.json#L118


https://github.com/irceline/aq-mobile-be/blob/0e3cab70dd17a56452ee7c9f6a46e6876d6e2c77/src/assets/i18n/fr.json#L118

https://github.com/irceline/aq-mobile-be/blob/0e3cab70dd17a56452ee7c9f6a46e6876d6e2c77/src/assets/i18n/en.json#L118

**Comment by opeeters** [comment]
translations have been added with 37efa4bcdabebf58afc2761be6f0256697d7788c
