### ISSUE TITLE
hmean and 24hmean are not in sync

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#176]
See:
![Screenshot_20190521-124305](https://user-images.githubusercontent.com/323719/58437206-3fe0f500-80c9-11e9-938f-9c859046cb31.png)

The last value of `hmean` and `24hmean` are not in sync. Something is going wrong. 

Also, sometimes the `24hmean` line is below the `hmean` line. Is it maybe possible to make sure the `24hmean` line is always on top?

**Comment by janschulte** [comment]
Fix the rendering order with: c49355a1c9e4be1a086f67a78d5d041427832288

The unsync state is fixed with: b4494110c0691f9dc4370f3bf2eefd249c201477

**Comment by opeeters** [comment]
Perfect!
