### ISSUE TITLE
Enter map view via 2nd user location goes to location of the first

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#177]
Steps to reproduce:
- configure more than one user location
- restart the app
- swipe to 2nd user location
- tap one of the long-term user location buttons (or click map via global navigation)

Result: The zoom is to the first user location
This should be to the user location in view at the time..

**Comment by janschulte** [comment]
Fixed with: 3a40fc3f410e78f63f2a3c5631e089e89946b448
