### ISSUE TITLE
no data in app with SdkVersion 28

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#178]
see: cf3ad39d0e8ec56383ad9c146fce0cfb28cda751
With `<preference name="android-targetSdkVersion" value="28" />` to comply with:
```
Play requires that new apps target at least Android 9.0 (API level 28), and that app updates target Android 9.0 from November 1, 2019.
```
see:
* https://developer.android.com/distribute/best-practices/develop/target-sdk.html

This triggers the following (so far only observed on: Huawei P20 lite - Android 9 - EMUI-version 9.1.0 - security patch 05/06/2019)
<details>
<summary>Screenshot</summary>
![1566818378553](https://user-images.githubusercontent.com/323719/63695560-43476200-c819-11e9-9a2c-2eab2ea44ad6.JPEG)
</details>
Even with multiple locations configured. Also clearing cache, adding new locations, using current location, etc. did not fix the issue.

On Galaxy S6 - Android 7 all is well.

**Comment by opeeters** [comment]
Doing a new build with setting `<preference name="android-targetSdkVersion" value="27" />` fixes the issue for `Huawei P20 lite - Android 9`

**Comment by SpeckiJ** [comment]
I can recreate the error with `<preference name="android-targetSdkVersion" value="28" />` on an AVM. The specific error is: `Failed to load resource: net::ERR_CLEARTEXT_NOT_PERMITTED` on the url: `http://www.irceline.be/air/time_app_json.php`.

This is caused by a change in the default value for the android:usesCleartextTraffic variable in Sdk 28, all http traffic is now blocked by default (see [here](https://developer.android.com/guide/topics/manifest/application-element) and search for `usesClearText`)

Alternative 1 (recommended): Use https for all endpoints.

Alternative 2: explicitly set android:usesCleartextTraffic in our AndroidManifest.xml

**Comment by SpeckiJ** [comment]
The relevant changes for Alternative 2:

```
--- a/config.xml
+++ b/config.xml
@@ -1,5 +1,5 @@
 <?xml version='1.0' encoding='utf-8'?>
-<widget android-versionCode="990" id="be.irceline.aqmobile" version="0.9.9" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
+<widget android-versionCode="990" id="be.irceline.aqmobile" version="0.9.9" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0">
     <name>BelAir</name>
     <description>Personalised air quality data throughout Belgium</description>
     <author email="belair@irceline.be" href="http://www.irceline.be/">The BelAir Team</author>
@@ -13,7 +13,7 @@
     <allow-intent href="geo:*" />
     <preference name="ScrollEnabled" value="false" />
     <preference name="android-minSdkVersion" value="19" />
-    <preference name="android-targetSdkVersion" value="27" />
+    <preference name="android-targetSdkVersion" value="28" />
     <preference name="BackupWebStorage" value="none" />
     <preference name="SplashMaintainAspectRatio" value="true" />
     <preference name="FadeSplashScreenDuration" value="300" />
@@ -24,6 +24,9 @@
     <platform name="android">
         <preference name="StatusBarOverlaysWebView" value="false" />
         <preference name="StatusBarStyle" value="lightcontent" />
+        <config-file parent="/manifest/application" target="AndroidManifest.xml">
+            <activity android:usesCleartextTraffic="true" />
+        </config-file>
         <allow-intent href="market:*" />
         <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
         <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />

```

**Comment by opeeters** [comment]
Everything from our infrastructure is available via `https`. 
@SpeckiJ I don't see a merge from feature/user-survey to feature/bugfixes before you committed your bugfixes. Will it be save to merge feature/bugfixes into feature/user-survey now and do a find and replace of http to https?

**Comment by SpeckiJ** [comment]
I have added a PR https://github.com/irceline/aq-mobile-be/pull/185/ incorporating the changes (including the refactor of http to https) into feature/user-survey.
