### ISSUE TITLE
Value pm10 is displayed for both pm10 and pm2.5 in nearest measuring station panel

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#179]
In the nearest measuring station panel, the values for `pm10` and `pm2.5` are always the same. The value displayed as `pm2.5` is actually the `pm10`. See:
![Screenshot_20190829-102346](https://user-images.githubusercontent.com/323719/63923696-49bb2100-ca47-11e9-8e38-c397bc8ccf04.png)

The REST-api serves the data correctly:
http://viewer.irceline.be/?ts=10762__irceline,10763__irceline&span=2019-08-22T17:56:44+02:00/2019-08-29T17:56:43+02:00

An in-app bug..

**Comment by janschulte** [comment]
Fixed with: 3acb144f348cae78bfc025cdc536807d5ba94f56
