### ISSUE TITLE
matching pm25_24hmean and pm10_24hmean does not work with stationnames with special characters

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#181]
See here:
![Screenshot_20190903-143502](https://user-images.githubusercontent.com/323719/64178200-51bcfb80-ce61-11e9-98d7-7102ffa57e18.png)

For stations:
* 42R805 - Antwerpen (Belgiëlei)
* 43H201 - Liège

The match goes wrong. Probably due to special characters in station name?

To reproduce:
- add e.g. user location "antwerpen-zuid"
- activate nearest measuring station

**Comment by janschulte** [comment]
e1d1f93917326a554a022ebe3a0406629bcf8c88 fixed it
