### ISSUE TITLE
add floating icon to questionnaire

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#183]
Add a floating icon bottom-right on the home-tab (maybe use the `md-megaphone` from the ionicons in a round floating element `--ion-color-primary: #389cc7;`). 
Once clicked a pop-up appears with the title "User Experience Survey" and text "Would you be prepared to answer a couple of questions on your experiences with this app?". 
Additionally two buttons:
1) "to the survey" > URL
2) "don't show again"
After the "don't show again" option has been activated, the icon is permanently hidden.

**Comment by janschulte** [comment]
Should the survey be activated/deactivated with app updates, or do we have somewhere a flag (e.g. in the time_app_json.php) which indicates if thie survey is active?

In my opinion the "flag"-way is more comfortable to handle and straighter at the user.

**Comment by opeeters** [comment]
Flag control is a good idea. Default value `0`. If active `1`. Should we ever remove the `survey` parameter from time_app_json.php, this should not cause any issues.

Test URL questionnaire:
* https://nl.surveymonkey.com/r/VNBBPD6

The following refinement propositions:
- When `"survey": "1"` show text `Help ons de app verbeteren` plus the icon at the bottom of the screen (maybe at min-width: 60%; max-width: 90%;)
- it should be possible to minimize text but keep icon bottom right (for users who want to return to the survey later).
- when icon or text are clicked, pop-up with `Bevraging gebruikservaring - Jouw feedback is belangrijk, ben je bereid enkele vragen te beantwoorden?. Het duurt slechts 2 min - Ok, zeker!` and button to make floating icon/text disappear permanently with text `Nee, bedankt`

What do you think?

**Comment by opeeters** [comment]
`"survey": "1"` has been added to `time_app_json.php`.

**Comment by janschulte** [comment]
> Flag control is a good idea. Default value `0`. If active `1`. Should we ever remove the `survey` parameter from time_app_json.php, this should not cause any issues.

I will handle a not existing `survey` parameter as value `0`.

> * When `"survey": "1"` show text `Help ons de app verbeteren` plus the icon at the bottom of the screen (maybe at min-width: 60%; max-width: 90%;)

I will check, if this is possible out of the box...

**Comment by janschulte** [comment]
See dc86c9791e60c7ae65f449e79a4e8f1e2e1c9481 for the implementation
