### ISSUE TITLE
Settings not loading correctly

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#186]
Settings are not loading correctly (Android build from master - both when deploying a build on device and via `npm serve`). 

See:

![Screenshot_20191204-103614](https://user-images.githubusercontent.com/323719/70132004-9b48fc80-1683-11ea-98d6-6fca0701e06d.png)

**Comment by opeeters** [comment]
Bug is not in `feature/local-leaflet-caching`

**Comment by janschulte** [comment]
Fixed this with: 1237639a29f8b6d9972b69a902558effe13fe4ee
