### ISSUE TITLE
Add location selector for case when no location can be established

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#187]
Add a selector to both the introduction wizard and when add a new location via the settings. In addition to the `search location` dialogue and `use current location` button a selector of e.g. a list from the postal service (both postal code and location name):

* http://www.bpost.be/site/nl/verzenden/adressering/zoek-een-postcode
* http://www.bpost.be/site/fr/envoyer/adressage/rechercher-un-code-postal

maybe run the list through:
* https://nominatim.openstreetmap.org

and use the returned `Centre Point`

**Comment by SpeckiJ** [comment]
Progress is tracked in branch : https://github.com/irceline/aq-mobile-be/tree/feature/location-creation-via-zipcode

Currently missing translations: 

https://github.com/irceline/aq-mobile-be/blob/595f7200eb6f9aa19421ab5d9f045b018a84076d/src/assets/i18n/nl.json#L501
https://github.com/irceline/aq-mobile-be/blob/595f7200eb6f9aa19421ab5d9f045b018a84076d/src/assets/i18n/fr.json#L501

**Comment by opeeters** [comment]
translations added with: 00f1965071bd8831d835e26ec7c3377c1cc897a1

All seems to work very well.
On small thing I was not able to fix. The leaflet controls are above the auto-complete results:

![Screenshot_20200121-164202](https://user-images.githubusercontent.com/323719/72820994-2734d900-3c70-11ea-9aa2-fb903c0046c5.png)

Steps to reproduce:
- create location
- type something
- add something so that the map appears
- look for different location

**Comment by SpeckiJ** [comment]
Thanks for the report :+1: 

Leaflet by default sets the control to z-layer 1000, die autocomplete bar to 999. I have adjusted the z-layer of leaflet controls to 998 in https://github.com/irceline/aq-mobile-be/commit/cd7dc007005a4bfe4f5d201186acef51fef6bc06 and the issue seems to be gone.
