### ISSUE TITLE
fix user-location-notification-toggler in create new location dialog

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#189]
The toggle in user-location-creation.component.html is not working.
Steps to reproduce:
- via settings, create new location
- activate notifications and save location
- return to settings, the notification icon is inactive (also the backend does not receive a registration for this new location)

When activating the notification for this new location in the settings, all is well and the location is registered via the backend.

**Comment by SpeckiJ** [comment]
This should be fixed with https://github.com/irceline/aq-mobile-be/commit/34ea39c587df76c9bd429b848b1147828d45e133.

Note: To test the functionality needs to be commented in first as it is commented out since https://github.com/irceline/aq-mobile-be/commit/ea8ca235181ef70118d2b8890dfdab2b080c8d91
