### ISSUE TITLE
setting user location when permission to use location service has not been granted yet

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#191]
In the introduction wizard, when trying to add new location via `use current location`, the system correctly asks permission:
![Screenshot_20191206-142005](https://user-images.githubusercontent.com/323719/70326064-dc800e80-1833-11ea-8654-dcefbf0bb8c4.png)

However, when clicking "Allow", you land here:
![Screenshot_20191206-142102](https://user-images.githubusercontent.com/323719/70326087-e3a71c80-1833-11ea-9181-da12a22c7448.png)
You need to click `use current location` again, which then works as expected..

**Comment by SpeckiJ** [comment]
This should be fixed with https://github.com/irceline/aq-mobile-be/commit/2276eb7cfaa771c10362998e8bb8cd53cd7af848.
