### ISSUE TITLE
`leaflet-control` hidden in iOS 13

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#194]
The `leaflet-control` elements top left in the map-tab are disappearing on iOS 13. See:

![Screenshot 2019-12-13 at 11 04 26](https://user-images.githubusercontent.com/323719/70792047-b0ffa580-1d98-11ea-83ec-b88ea1b9918a.png)

Probably a `z-index` has to be explicitly be declared since iOS 13.

**Comment by opeeters** [comment]
Maybe update `@helgoland/map` or pin leaflet to higher version?

**Comment by opeeters** [comment]
updating to:
```
    "@helgoland/core": "1.0.0-beta.8",
    "@helgoland/d3": "1.0.0-beta.8",
    "@helgoland/map": "1.0.0-beta.8",
```
Gives the following build-error:
```
ERROR in src/app/components/belaqi-map-slider/belaqi-map-slider.component.ts(1014,9): error TS2322: Type '{ layers: string; transparent: true; format: string; tiled: string; opacity: number; hideInOpacitySlider: boolean; boundary: GeoJsonObject; useBoundaryGreaterAsZoom: number; }' is not assignable to type 'BoundaryCanvasOptions'.
  Object literal may only specify known properties, and 'tiled' does not exist in type 'BoundaryCanvasOptions'.
src/app/components/belaqi-map-slider/belaqi-map-slider.component.ts(1021,22): error TS2339: Property 'time' does not exist on type 'BoundaryCanvasOptions'.
src/app/services/geo-search/geo-search.service.ts(42,78): error TS2339: Property 'map' does not exist on type 'Observable<any>'.
src/app/services/geo-search/geo-search.service.ts(84,120): error TS2339: Property 'map' does not exist on type 'Observable<any>'.

[ERROR] An error occurred while running subprocess ng.
```

**Comment by SpeckiJ** [comment]
helgoland 1.0.0 is a ng8 based development and therefore not suited for the App. The latest suitable Version is 0.0.1-beta.9

The Bug is probably based on a change in Webkit in ios13, similar to the issues leading to wrong paths (intended for legacy browsers). (see: https://github.com/Leaflet/Leaflet/issues/6817 or https://github.com/Leaflet/Leaflet/issues/6889)

Leaflet 1.6.0 fixes the interaction issues, unfortunately the controls are still invisible sometimes. We are still investigating.

**Comment by SpeckiJ** [comment]
The issue seems to be fixed by forcing hardware accellerated rendering on the leaflet control components as suggested in https://github.com/Leaflet/Leaflet/issues/4673

**Comment by SpeckiJ** [comment]
A fix for the invisible controls is commited in https://github.com/irceline/aq-mobile-be/commit/fdad21e66e2a89f84ee3a4c6fb27b036a350e8c3.

Now only Leaflet needs to be upgraded to 1.6.0 in the helgoland dependency (to fix the other interaction issues). @janschulte

**Comment by janschulte** [comment]
Adjust toolbox version with leaflet 1.6 now in 23b956998e5937b71fade9ca5dfa07cecb7a0cb6
