### ISSUE TITLE
Input location not responding on iOS iPhone X

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#195]
When creating a location (manual input in the search), the request seems not performed on an iPhone after clicking "go".

See:

https://cloud.irceline.be/index.php/s/XkxciREP4Q3KLZp

Not reproducible in simulators.

**Comment by janschulte** [comment]
It is hopefully this issue: https://github.com/angular/angular/issues/32963

Sadly I cannot test it, but I created a fix branch: https://github.com/irceline/aq-mobile-be/tree/fix/195

**Comment by opeeters** [comment]
Thanks, will test and get back to you..

**Comment by opeeters** [comment]
Seems to work on device
