### ISSUE TITLE
in-app display push-notification displays old notification

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#196]
When sending a push-notification and adapting:
https://www.irceline.be/air/belair/channel/flanders.json
the in-app display of the message also shows a previous message:
![Screenshot_20200123-124151_BelAir](https://user-images.githubusercontent.com/323719/72982107-9fb9a800-3dde-11ea-92a6-7ad55c3fe1cf.jpg)

**Comment by SpeckiJ** [comment]
Unfortunately I do not quite understand what has happened prior to this visual feedback.

From your description I get the following timeline:

1. JSON Document was created and deployed to `/air/belair/channel/flanders.json`
2. Firebase Notification was sent
3. Notification was received & displayed by the app. The notification is now cached and will be shown until `expiration` date is reached.
4. The JSON Document at  `/air/belair/channel/flanders.json` was changed, but **no second firebase notification** was send.
5. The App now shows both notifications until their respective `expiration` date is reached.

Is this timeline correct @opeeters ?

**Comment by opeeters** [comment]
Maybe I have found what cause the error. There was a syntax error in:
https://www.irceline.be/air/belair/channel/flanders.json
I added the file to the webserver with `vi` and must have pressed `i` twice.. the json started with an `i` instead of `{`. Fixing this seems to resolve the issue.

But still, the message which was displayed should not have been displayed.

Here is what I did:
1) send Firebase notification to https://fcm.googleapis.com/fcm/send
2) remembered that https://www.irceline.be/air/belair/channel/flanders.json should be updated too and added a json (with a syntax error)
3) the notification was correctly received by users
4) the in-app display of the notification displayed both the message as intended and an old message also for users who only opened the app when https://www.irceline.be/air/belair/channel/flanders.json was already updated (but with syntax error)

I assume that due to the syntax error the last message in the app data was displayed even though the corresponding expiration was already several months ago?

It would be better to stop this from happening, but I'll be more careful next time...

**Comment by SpeckiJ** [comment]
Thanks for the explanation - that cleared up some questions. I was unaware that the other message shown was a message that has expired long ago, I thought it was the text that stood there earlier (prior to the correction) and the correction only updated the text.

So it seems we may have a flaw in the deletion of old notifications after they have expired. I will look into this tomorrow.

**Comment by opeeters** [comment]
Shall we add a test-channel for testing? A bit dangerous though, no?

**Comment by opeeters** [comment]
tested.. all is well
