### ISSUE TITLE
fix caching issue forecasts

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#198]
There is a structural problem with the caching of forecast maps. The forecast for today (d0), tomorrow (d1), today+2 (d2) and today+3 (d3) get updated several times per day. When zooming in or out you might get cached tiles from different forecast versions, which is confusing and not (always) the best available forecast for a given day.

The only way to solve this is to call the forecast layer with the timestamp of the last update:
https://www.irceline.be/air/time_app_forecast_json.php
and have a WMS-layer per forecast day (via `forecastWmsURL`):

- belaqi_d0
- belaqi_d1
- belaqi_d2
- belaqi_d3

- no2_maxhmean_d0
- no2_maxhmean_d1
- no2_maxhmean_d2
- no2_maxhmean_d3

- idem for o3_maxhmean_dX, pm10_dmean_dX, pm25_dmean_dX

This logic needs to be added to src/app/components/belaqi-map-slider/belaqi-map-slider.component.ts
but, does this also have consequences for the caching?

**Comment by SpeckiJ** [comment]
I have implemented the changes in 
a1a8e36 and created a seperate branch to track the feature: https://github.com/irceline/aq-mobile-be/tree/feature/forecast_update

I have not yet tested the implementation fully as I did not find a time when I had the App open and a forecast layer is updated. Are there specific predictable times when that happens? @opeeters

For caching I propose tracking the changes needed there in #109 as this feature is independent from the caching per se

**Comment by opeeters** [comment]
@SpeckiJ 
Currently the forecasting layers are triggered to update at 1h10, 8h10 and 13h10 CEST. There might be manual triggers in between, but these updates are the predictable ones.

As for the caching, as long as feature/forecast_update can be tested separately (but than, without the caching).. fine by me.

My planned path to release 1.0.1 is:
1) merge master into feature/forecast_update (done by you already)
2) limited testing Android + iOS
3) merge feature/forecast_update into feature/local-leaflet-caching (apparently also done by you already - see, we are thinking the same thoughts :-)
4) limited testing Android + iOS -> make a choice between feature/forecast_update and feature/local-leaflet-caching for release 1.0.1, but feature/local-leaflet-caching was tested already, so this will probably become the release
5) extensively test notifications, forecasts and caching of the release candidate
6) internal release

**Comment by janschulte** [comment]
Olav, there is one open issue regarding the caching of WMS tiles. We determine, that the caching of tiles and the boundary machanism (intersection between WMS tiles and the configured geometry for higher zoom level) not work beside together.

Do you still need this boundary mechanism?
 - if not, we are quite ready to merge the branches together
 - if yes, we need more investigation, how to solve working both together

**Comment by SpeckiJ** [comment]
Note: This only affects the branch https://github.com/irceline/aq-mobile-be/tree/feature/local-leaflet-caching-

https://github.com/irceline/aq-mobile-be/tree/feature/forecast_update can be merged as-is as it does not mess with any tiles directly

**Comment by opeeters** [comment]
@janschulte I'm not quite sure what you mean here? Something related to this issue maybe: #171

**Comment by janschulte** [comment]
> @janschulte I'm not quite sure what you mean here? Something related to this issue maybe: #171

No, I mean the previously added funtionality that on higher zoomlevels only parts of the layer are displayed on the map. Back then I believe we have add this feature, because the measurement density in the area of Antwerpen (Which leads to better resolutions of the layers in this area) was higher, than in the rest of Belgium.
Currently the defined area matches complete Flanders, as I saw yesterday while checking this issue.

I didn't find a regarding issue to this feature, maybe we defined it in a Telco or by mail.

**Comment by opeeters** [comment]
In the beginning the higher zoom levels were indeed only available for Antwerp, than the whole of Flanders. Later Brussels was added. Currently, the higher zoom levels are deactivated for Wallonia only. I will get back to you asap. Maybe we can drop the mechanism now..

**Comment by opeeters** [comment]
We have to keep the functionality, I'm afraid. The data for Wallonia not yet ready for closer scrutiny.

**Comment by janschulte** [comment]
It wasa hard issue, but I have hopefully combined the boundary mechanism with the caching. Done with: a8303aa1088bf0e0471446c7217ee4a6dad92903
