### ISSUE TITLE
slow map loading with feature/local-leaflet-caching

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#200]
In a build of the feature/local-leaflet-caching all the maps in map-view load noticeably slower. Really slow.. it takes more than 20 seconds for a tile to appear.

**Comment by SpeckiJ** [comment]
Unfortunately i cannot recreate this behaviour on Android 8.0.0 nor in the browser app.

Depending on network speed the tiles load in 100ms (unthrottled network speed) to max. 5s (all taken up from the network request, tested with "Slow 3G" in Chrome DevTools). Loading from cache with no internet connection took ~40ms on my Galaxy S7.

Were there any special circumstancen when this occurred? E.g. directly after App start (where other processes might run)?

**Comment by opeeters** [comment]
Android 7.0, Galaxy S6
On my device the behaviour occurs both directly after app start (with and without a network connection) and even when revisiting a previously loaded parameter in the same session (I would assume that this would be from cache).
I will test this on other devices and get back to you...

**Comment by opeeters** [comment]
I also still have this issue in browser (npm start) on the `52n-v2-upgrade` branch. It takes at least 10 seconds to load tiles from cache.

**Comment by opeeters** [comment]
On device this does not seem to be a problem. But maybe related, when changing the position of the time line, multiple layers are displayed above each other.

**Comment by opeeters** [comment]
remains difficult to reproduce..
