### ISSUE TITLE
Belaqi indices for start view

### ISSUE THREAD

**Issue by janschulte** [irceline/aq-mobile-be#203]
How should we gather the indices on the start view for the past (in days), the current (normaly last hour) and the forcast (in days).

I the last version we used the following mechanism: 
- past: Request on https://geo.irceline.be/rioifdm/belaqi/wms with layer `rioifdm:belaqi` and past hourly timestamp
- current: Request on https://geo.irceline.be/rioifdm/belaqi/wms with layer `rioifdm:belaqi` and current timestamp
- forecast: Calculated Values for future Hours

Now we need daily values for the past and the forecast, where or how should these values be gathered?

**Comment by opeeters** [comment]
* the `a few seconds ago` index comes will be changed to `today` and comes from `forecast:belaqi_d0` on https://geo.irceline.be/forecast/wms
* `in a day` is `forecast:belaqi_d1` (same endpoint)
* `in 2 days` is `forecast:belaqi_d2` (same endpoint)
* `in 3 days` is `forecast:belaqi_d3` (same endpoint)

* `a day ago`, `2 days ago`, etc. will be `rioifdm:belaqi_dmean` from https://geo.irceline.be/rioifdm/wms (layer is under construction)

**Comment by janschulte** [comment]
Currently I get here a not rounded index: https://geo.irceline.be/forecast/wms?request=GetFeatureInfo&bbox=5.6100672,50.759122399999995,5.610077199999999,50.7591324&service=WMS&info_format=application/json&query_layers=forecast:belaqi_d1&layers=forecast:belaqi_d1&width=1&height=1&srs=EPSG:4326&version=1.1.1&X=1&Y=1

Should the App round to the next index?

**Comment by janschulte** [comment]
TODO: Use forecast update time

**Comment by opeeters** [comment]
https://www.irceline.be/air/timestring_forecast.php

**Comment by opeeters** [comment]
`rioifdm:belaqi_dmean` can be used for `a day ago`, `2 days ago`, etc. now from https://geo.irceline.be/rioifdm/wms

The time parameter has the following structure: YYYY-MM-DD (e.g. 2020-06-24).
