### ISSUE TITLE
Modelled Values in the Details view

### ISSUE THREAD

**Issue by janschulte** [irceline/aq-mobile-be#204]
Just to clarify, in the current version we use for the short-term exposure this WMS (https://geo.irceline.be/rioifdm/wms) with the layers: 
- rioifdm:no2_hmean
- rioifdm:o3_hmean
- rioifdm:pm10_24hmean
- rioifdm:pm25_24hmean

For the long-term exposure we currently use the year 2017 (https://www.irceline.be/air/timestring_rioifdm_anmean.php) and the following WMS (https://geo.irceline.be/rioifdm/no2_anmean_2017_atmostreet/) for NO2. Other phenomenons in a similar way.

![image](https://user-images.githubusercontent.com/3830314/85110618-7416de80-b213-11ea-8233-518cd9ee89d8.png)
In the new  BelAir version the calculated value for a  phenomenon should be the old short-term exposure and the middled value will be the long-term exposure. Am I right here?

**Comment by opeeters** [comment]
Yes, the mean value (`gemiddeld`) comes from the `anmean` values. The `berekend op jouw locatie` comes from the `hmean` or `24hmean` data layers in BelAir v2.
