### ISSUE TITLE
Details for a specific Phenomenon

### ISSUE THREAD

**Issue by janschulte** [irceline/aq-mobile-be#205]
![image](https://user-images.githubusercontent.com/3830314/85113313-5c415980-b217-11ea-8dc5-6af6f5bbcd4a.png)

Two open questions for this section:
- How and where should the app gather the time specific values. Is the also a WMS with the phenomenon specific layer and the option to request the value for different timestamps?
- Should the map show this different layers, when the user changes the time?

**Comment by opeeters** [comment]
The maps of the sub-indices should be the `hmean` or `24hmean` of the lastupdate from here:
https://www.irceline.be/air/time_app_json.php

A time scroller could be a nice addition in the future, maybe something simple, just arrows & a timestamp, cf:
https://geo.irceline.be/www/o3_hmean_rioifdm_EN.html

e.g. add a timechanger under the map

**Comment by opeeters** [comment]
The daily value for the last couple of days in the ribbon above will be the following:

- pm10 & pm25
from https://geo.irceline.be/rioifdm/wms
`pm10_24hmean` and `pm25_24hmean` @ time=2020-06-25T00:00:00.000Z as `dmean` of 2020-06-24, etc.
The `dmean` is the mean value of all hmean of a day in UTC. Problem is that, especially in summer, the dmean of the day before will only be ready at about 02h55. Maybe the easiest will be to keep the app in a state of the previous day until 03h00? Or use the 24hmean of T22:00:00.000Z, T23:00:00.000Z as temporary dmeans for the previous day?

- o3 & no2
from https://geo.irceline.be/rioifdm/wms
`o3_maxhmean` and `no2_maxhmean`
`time` should be managed similar to `pm10_24hmean` and `pm25_24hmean`

**Comment by janschulte** [comment]
Maybe the best option is, to get somewhere the information, that the calcuation of all layers for the last day is finished?

And two new questions:
- Should the map layer also be adjusted, when the user selects another day?
- What's about forecast values? Do you have also predictive layer for every phenomenon?

**Comment by opeeters** [comment]
Maybe use `timestring_day` for this? From here:
https://www.irceline.be/air/time_app_json.php
Or is this still used elsewhere?
Maybe add a `lastupdate_day` instead?

Yes, the map should be switched to the selected day (`day ago`> the relevant 24hmean or maxhmean layer - to the future > the relevant forecast)

**Comment by opeeters** [comment]
The relevant forecast layers are (from https://geo.irceline.be/forecast/wms):
forecast:no2_maxhmean_d0 (forecast for today)
forecast:no2_maxhmean_d1 (tomorrow)
forecast:no2_maxhmean_d2
forecast:no2_maxhmean_d3

forecast:o3_maxhmean_d0 (forecast for today)
forecast:o3_maxhmean_d1 (tomorrow)
forecast:o3_maxhmean_d2
forecast:o3_maxhmean_d3

forecast:pm10_dmean_d0 (forecast for today)
forecast:pm10_dmean_d1 (tomorrow)
forecast:pm10_dmean_d2
forecast:pm10_dmean_d3

idem pm25

The current value + map should be (from https://geo.irceline.be/rioifdm/wms):
rioifdm:no2_hmean
rioifdm:o3_hmean
rioifdm:pm25_24hmean
rioifdm:pm10_24hmean

**Comment by janschulte** [comment]
- `o3_maxhmean` and `no2_maxhmean` currently doesn't exist on https://geo.irceline.be/rioifdm/wms

- When do you plan to publish the `lastupdate_day` in https://www.irceline.be/air/time_app_json.php ? Then I can implement the complete workflow to fetch the past values.

**Comment by opeeters** [comment]
`lastupdate_day` has been added to https://www.irceline.be/air/time_app_json.php

`o3_maxhmean` and `no2_maxhmean`will be added a.s.a.p. to https://geo.irceline.be/rioifdm/wms

**Comment by opeeters** [comment]
`o3_maxhmean` and `no2_maxhmean` are available now

**Comment by janschulte** [comment]
Thanks, but the `lastupdate_day` hast currently the value `2020-06-28T02:00:00+02:00`, is this right? I assumed it should be `2020-06-29T02:00:00+02:00`?

And the layers are not named `o3_maxhmean` and `no2_maxhmean`, they have the names `o3_maxhmean_rioifdm` and  `no2_maxhmean_rioifdm`. I will use these two...

**Comment by opeeters** [comment]
You're right about the `lastupdate_day`. Bug in the integration script.. has been corrected.

I rename the layers to `o3_maxhmean` and `no2_maxhmean`. I was doing to many things at the same time :-)

**Comment by janschulte** [comment]
This should also work now. Main implementation happens in 0ea92e0a2c8f113b5d88aa12a2915ff649fec6c6
