### ISSUE TITLE
automatic selection pollutant map view > diagram view

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#21]
When clicking on station in map view, the pollutant of the particular map view should be automatically be selected, with e.g. an option "other pollutant measured on this location"

**Comment by janschulte** [comment]
Added with 1a6cb0f04498d7e489935791b0710391ca064f42

**Comment by opeeters** [comment]
The pollutant is not selected. See:

![screenshot_20180903-165232](https://user-images.githubusercontent.com/323719/44993451-ebc23d80-af9a-11e8-912c-63d8f6ed3dfc.png)

The other pollutants are however hid as expected.
