### ISSUE TITLE
time line is positioned on the value "3 days ago" instead of current value

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#210]
When loading the app, the time line is positioned on the value "3 days ago":
![Screenshot_20200630-093442](https://user-images.githubusercontent.com/323719/86098376-502a8700-bab6-11ea-8074-e7449fe19508.jpg)

This should be the current value:

![Screenshot_20200630-093757](https://user-images.githubusercontent.com/323719/86098418-5f113980-bab6-11ea-915b-bc8d38c59e28.jpg)

**Comment by opeeters** [comment]
This should also be fixed on the detail-tabs

**Comment by janschulte** [comment]
Done for both with: 56fbac2c18eb2c3385c227ad1b542b2ec43cd5ac

**Comment by opeeters** [comment]
Looking good!
