### ISSUE TITLE
reduce size of APK

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#211]
Currently a development build results in a package of about 75MB. A production build still is about 64MB. Let's see if we can reduce this..

**Comment by janschulte** [comment]
Maybe checking unused plugins

**Comment by SpeckiJ** [comment]
![apksize](https://user-images.githubusercontent.com/13851077/87776924-d837bd00-c828-11ea-89de-a31f2c6dd993.png)

Debugging the APK shows that most of the space is used by the png backgrounds (see Screenshot, list goes on further but was omitted for readibilty).

**Comment by opeeters** [comment]
OK, thanks, @SpeckiJ . We replaced these png's with a couple of .svg's meanwhile. I'll discus it with the UI people, but I think that nearly all can go. I didn't think these would be pulled into the build..

**Comment by opeeters** [comment]
@kresogalic8 All the png's in src/assets/images/backgrounds could be remove now, no? Or how can we prevent them from being pulled into the build? We want to reduce the size of the build.. (around 70MB where the old app was about 7MB)

**Comment by opeeters** [comment]
Hmm, I see they are referenced in the config.xml as icons. Maybe to svg-icons?
