### ISSUE TITLE
Location service not working on device

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#212]
After being prompted to allow access to the location service the eternal spinning wheel of joy keeps spinning:

![Screenshot_20200630-095606](https://user-images.githubusercontent.com/323719/86099728-2b371380-bab8-11ea-8e2e-3239d14eceff.jpg)

**Comment by janschulte** [comment]
Implemented with: 09163f97851ceef29bd33a0c738353ffd6dc793b and af01734161e2a15bc8c405c3afba4ce7c04da7e8
