### ISSUE TITLE
Multiple map layers are displayed above each other in the detail view upon timeline change

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#214]
When changing the position of the time line in a detail view tab, multiple layers are displayed above each other on the map.

**Comment by opeeters** [comment]
Revise loading mechanism

**Comment by janschulte** [comment]
Slight optimization done with  7d2733576a24919b3d94a16352b40ac123133da9

**Comment by opeeters** [comment]
moving this to milestone 1.7.2. When layers are read from cache all seems well. When loaded from server, the loading still seems a little zippy.

**Comment by opeeters** [comment]
looks good!
