### ISSUE TITLE
trigger refresh app

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#216]
The refresh being triggered by swiping downwards on a tab (cf BelAir 1.0) has been disabled. This could be useful in the following situations:

- The app is open for some time. A new hourly update of the BelAQI is available.

- Currently, when e.g. going to the feedback tab, the background is still added ad random.. Going back to the landing tab, this state is kept. It should be possible to refresh the state of a tab in such an instance.

**Comment by janschulte** [comment]
Done with: 1ecb7d2ef85403a24f745b6a5343fb8272399e42

**Comment by opeeters** [comment]
The refresh data works well for all the random locations automatically configured on first launch, but not for any locations which were added by the user. This persists when all random location have been removed. Missing data is not fetched when triggering refresh.

**Comment by janschulte** [comment]
Sorry, but I doesn't understand this problem. Do you mean the complete empty view which still shows some data? I expect, that a solution for an empty location list will be resolved with the issue #222? Or is there an other problem, I doesn't see?

**Comment by opeeters** [comment]
This is unrelated to #222. As a test open the app with some user locations set and some random locations. At the moment no belaqi_dmean's are present for the last three days on the server. Let me know when you're ready. I will trigger the update of the belaqi_dmean's one by one. when you trigger the refresh in the app you will see that all random locations (locations that do not have a "type":"user" set) are refreshed, meaning the the new data is fetched. For locations which are fetch internally with localStorage.getItem(userLocationsLSkey) this is not happening.

**Comment by janschulte** [comment]
I checked a lot in this case, but I still doesn't see a coherence between the different locations. 

I saw one behaviour, which can explain your experience. There are requests on the dmean layer which results in an empty result. These empty result is cached and on a user initiated refresh, there will be still the cached data delivered.

So, what is your exact expectation here? Should a refresh load all the data again and clear the cache at this state, or just try to reload the data, which was before unreasonable?

**Comment by opeeters** [comment]
This can explain what I observed. Maybe the other locations did not yet have cached data yet.

On triggering a refresh, I would expect new data request being send to the server. After a time-out (e.g. 20 seconds) the app could go back to the cache instead (e.g. when servers are down). 

But would it not also be possible to prevent the app from caching empty results?

**Comment by janschulte** [comment]
Base on the agreement in the last telco, the requests with empty results will not be cached anymore.

Implemented in e169513d13d681818fb07cd4f90278a0ccf8d443

**Comment by opeeters** [comment]
Thanks!
