### ISSUE TITLE
longterm data

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#217]
Depending on the lastupdate value from here:
https://www.irceline.be/air/timestring_rioifdm_anmean.php
(do you prefer a json version? Could also be added to https://www.irceline.be/air/time_app_json.php)

The layers are (from https://geo.irceline.be/rioifdm/${layerId}/wms) e.g.:
rioifdm:o3_anmean_2017
rioifdm:o3_anmean_2016
...
the year of the lastupdate + the 4 previous years

Or more generic:
rioifdm:${layerId}_${year}

where `layerId` can be:
o3_anmean
no2_anmean
pm10_anmean
pm25_anmean

**Comment by janschulte** [comment]
> (do you prefer a json version? Could also be added to https://www.irceline.be/air/time_app_json.php)

Yes, if possible please add it to. One less request.

And some questions: 

- Where can I get the EU and World limit values shown in the long term screen for each phenomenon?
- Which location should be used, when the user navigates to the longterm screen via the menu? Also I don't understand, why the longterm option is shown in the menu? The navigation also doesn't work on that point. You go to the longterm screen, then go back and lands on the start screen and not in the menu? It is confusing, maybe the best option is to remove navigation option in the menu to this longterm screen?

**Comment by opeeters** [comment]
Concerning the limits, probably we will only add it to PM2.5 and NO2. The other parameter have limit values which are not so easily made comparable. Let's use the following:

NO2: 25 ug/m3 (WHO) and 40 ug/m3 (EU)
PM2.5: 10 ug/m3 (WHO) and 25 ug/m3 (EU)

Concerning the navigation, in all cases go to the longterm tab for the location that is currently active on the landing tab. It would make sense if you could change between locations on the longterm tab as elsewhere in the app. Can we maybe add the swiper above or below the longterm-info div?

I agree that the longterm link in the menu is a bit strange. But leave it like it is for the time being. Just go to the longterm info for the location last active or of the current landing tab.

**Comment by opeeters** [comment]
"lastupdate_year" has been added to: https://www.irceline.be/air/time_app_json.php

**Comment by janschulte** [comment]
Done with b9af35f9e775b3c7c2ce43bbc7321ff7d286a2a0 and 0edb70c9f7ed2e0675ff8931e8f3feda335cda9f

**Comment by opeeters** [comment]
Looking good. Thanks!
