### ISSUE TITLE
strange trend line

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#221]
Currently, the trend line given by the app (v1) looks rather strange:

![Screenshot_20200702-124556](https://user-images.githubusercontent.com/323719/86355671-544bd580-bc6b-11ea-8ab1-56a7c3661dc5.jpg)

I checked all data services (data layers) + time and trend data from:
https://www.irceline.be/air/time_app_json.php
https://www.irceline.be/air/forecast/trend.php

Any ideas what might be going wrong? I would assume this has to do with some server-side resource since I have never seen this before. Or will this disappear again as soon as there is more air pollution again :-)?

**Comment by opeeters** [comment]
Getting even more funky:

![Screenshot_20200702-142441](https://user-images.githubusercontent.com/323719/86358559-f372cc00-bc6f-11ea-90ca-58f4b842ddd8.jpg)

**Comment by janschulte** [comment]
Commit message autocloses these issue...

**Comment by opeeters** [comment]
Having a look at the commit if seems something related to the NO2-subindex. Since the trend data is in the app we will only be able to fix this with an update. Under which circumstance would it be hiden again? Higher values of the other sub-indices?

**Comment by janschulte** [comment]
This happens allways, when the no2 trend is not the same as the calculated max trend out of the 4 parameters. Then there are addtional trendlines visible, because the error produces three parallel trends lines for the next 24 hours instead of one trend line for the next 72 hours.
