### ISSUE TITLE
system back button not working

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#224]
Steps to reproduce:
- launch app
- terminate intro
- click info-button
- hit back button

**Comment by SpeckiJ** [comment]
The previous custom backButton implementation from v1 can be found here: https://github.com/irceline/aq-mobile-be/blob/357d5e00abe187054731091f5168cdba0a2fdd76/src/app/app.component.ts#L37

**Comment by opeeters** [comment]
Probably we need to remember the last two tabs a user has accessed to be able to go down this navigation history? Assuming that within 2 moves you're back on the landing tab in most cases.

**Comment by opeeters** [comment]
The back-button does not work on the following tabs:
- app-info
- the settings
- the feedback tab
It's sufficient to find a solution for these three cases.

**Comment by opeeters** [comment]
Looking good, thanks!

**Comment by opeeters** [comment]
On closer inspection, the above fix disabled the `exitApp();` when a user is already on the landing tab, the expected behaviour in Android.

**Comment by opeeters** [comment]
I tried including function backButtonEvent() and storeLastNavigation() (cf c4e7e7648ace3e8df8c61a85fea9aec24e22c7a7), which kind of works, but the storeLastNavigation() is not doing it's job it seems. The app is just always closing on hitting the hardware back button.

**Comment by janschulte** [comment]
Now the app only exited, while being on the main screen.
