### ISSUE TITLE
update version number in settings

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#225]
Update the app version number at the bottom of the settings:

![Screenshot_20200708-145045](https://user-images.githubusercontent.com/323719/86920845-98871c00-c12a-11ea-837f-87cfa7530a74.jpg)

**Comment by janschulte** [comment]
Done with: 31f714a404562339003b2222d1a05ecad93278a3

**Comment by opeeters** [comment]
Thanks!
