### ISSUE TITLE
finding location via location service is slow

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#227]
At the moment it takes a bit to long (ca 20 seconds) to find a location in very good conditions (wifi connection, next to a window, having been at the same location for some time, location service activated). Probably we can improve this by playing with the timings (timestamp of last known location in the log)?

**Comment by janschulte** [comment]
https://github.com/irceline/aq-mobile-be/issues/170

**Comment by opeeters** [comment]
tweaked with 7524bb2596ed605f40e4026f34a74ec27ca5f27c

Seems to be better now.
