### ISSUE TITLE
display text (or animation) when long-term data is being loaded

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#228]
display translatable text (or animation when available) on the long-term tab when data is being fetched

**Comment by janschulte** [comment]
@opeeters Am I right, that you assigned the wrong issue to you? This one is for me and #227 your's?

**Comment by opeeters** [comment]
It's a shared one. I also assigned it to me since I need to cater for an animation for the long-term. But yes, please provide a translatable text for the duration of the data-loading.

**Comment by janschulte** [comment]
Implemented with: d42fa45ce9d9ddc1bbe3f0d3c9664681b3c46026

**Comment by opeeters** [comment]
Closing issue. Text and spinner work well enough I think.
