### ISSUE TITLE
add information icon to map view with legend + other info about pollutant

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#23]
start with these legends:
http://www.irceline.be/air/legend/bc_hmean_EN.svg
http://www.irceline.be/air/legend/no2_hmean_EN.svg
http://www.irceline.be/air/legend/o3_hmean_EN.svg
http://www.irceline.be/air/legend/pm10_hmean_EN.svg
http://www.irceline.be/air/legend/pm25_hmean_EN.svg

Change to language code to NL, FR or DE in accordance with language settings of app.
The bootstrap glyphicon-info-sign should be fine to start with.

**Comment by janschulte** [comment]
Added with cb4de955c9392d68c3156a4a8856f860791659ed
