### ISSUE TITLE
Make it impossible to add the same location more than once

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#233]
Both for a location entered via auto-complete and by using the location service of the device, it is possible to enter the same location multiple times:

![Screenshot_20200717-162627_BelAir_v2](https://user-images.githubusercontent.com/323719/87803979-86585c80-c853-11ea-8e75-2613d50e24e0.jpg)

**Comment by opeeters** [comment]
also add a feedback when the same location is added a second time.

**Comment by SpeckiJ** [comment]
I will look into it and update this issue when a PR is ready

**Comment by SpeckiJ** [comment]
I have added a duplicate check (based on the location label) in https://github.com/irceline/aq-mobile-be/commit/888ced0c85929adc94547306c772086fb78eb1d7

Currently if there is a duplicate location it is just silently dropped, as I could not find any error display in the frontend. But I found it pretty intuitive, after adding the location it is in the list (whether it was previously there or not) so I do think an error message could be more distracting than just this behaviour.

**Comment by opeeters** [comment]
This solution works well for locations add via auto-complete. 
It is however still possible to add duplicated via the location service. I guess the check also needs to be added to the function which adds a location via `current location`.

**Comment by SpeckiJ** [comment]
> I guess the check also needs to be added to the function which adds a location via current location.

This would prevent you from adding e.g. Brussels while you are actively there, I think that would be confusing as you might not always be in Brussels and actually want it in your location list.

Additionally, as the `current location` also changes frequently, the list of stored locations would also have to update to always remove the location where you currently are (as it is a duplicate) before re-adding it later once you moved on (as it is not duplicate anymore).

**Comment by opeeters** [comment]
At the moment, as far as I know, not the current location, but the centroid of the commune closest to the current location is stored. Hence using the current location to store e.g. multiple instances of Brussels will create 100% duplication. This might still change at a later stage, but for the time being we should prevent duplication since it comes across as buggy.

Ideally (in the future when the location functionality allows a higher degree of customisation), the check should be on a combination of location name and lat/long. But for the time being a check on location name is sufficient I think.

**Comment by SpeckiJ** [comment]
So we need to check when the `current location` changes to a place which is already in the location list to remove that location from the list, store it offline, and when the `current location` changes away we need to restore the location from offline storage.

I will look into it today/tomorrow and update this issue once a first implementation is ready.

**Comment by opeeters** [comment]
Check needs to be done when a match is made between the current location and the closest location on the list (which is also used by the auto-complete). Every new entry to the stored user locations should just be checked for duplication before being added.

**Comment by SpeckiJ** [comment]
I have looked into it more together with @simonjirka. The Problem I had is that I still had the old semantic of `current location` from v1 in mind, where the location changes frequently, not the semantic from v2 where it is a `location of the closest station`.

Since https://github.com/irceline/aq-mobile-be/commit/30bd2d97dfb143f1468180e58a2e046c9bb34d65 the location is properly filtered out before adding it to the list.
