### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by SpeckiJ** [irceline/aq-mobile-be#234]
While searching through the App is stumbled upon some hardcoded Strings in the HTML templates which are missing translations:

https://github.com/irceline/aq-mobile-be/blob/762dea182ec61940aa7cf00f4ca868685bd5113f/src/app/v2/components/information-item/information-item.component.html#L23

https://github.com/irceline/aq-mobile-be/blob/762dea182ec61940aa7cf00f4ca868685bd5113f/src/app/v2/components/information-item/information-item.component.html#L26

Is this desired (e.g. old development artifacts not used) or should translations be added for these constants?

**Comment by opeeters** [comment]
Thanks @SpeckiJ I'll take it from here. If you come across any others, please let us know.
