### ISSUE TITLE
Incorrect Belaqi-Index display on no location/no data available

### ISSUE THREAD

**Issue by SpeckiJ** [irceline/aq-mobile-be#237]
There are some issues with the App being offline and the displayed Data:

1. When there are no locations registered, the belaqi index wheel is still shown and says "good". This could be misinterpreted easily (e.g. as "current value on my location is good").

2. Connected to that: when adding a new location in offline Mode (or starting the app with the current "random locations" in offline mode), the belaqi Index shows as "good" by default, without any access to data! 

A default background (outside of the normal belaqi color scale) would help to distinguish those cases from just normal operation. I think displaying "good" even though there is no location and/or no data is pretty misleading.

**Comment by opeeters** [comment]
In src/app/v2/services/bel-aqi.service.ts a default `indexScore`  is set. This is expected behaviour. We could also set this to `0` instead to have a longer dial animation.
