### ISSUE TITLE
add BelAQI and Black Carbon to "view in detail"

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#240]
![03_Home_PULLTAB](https://user-images.githubusercontent.com/323719/97417440-fb820600-1907-11eb-922f-c989644683db.png)

**Comment by janschulte** [comment]
For the details map view we currently have not defined layers for the past and forecast values of black carbon. Can you provide some? For the current value I used `rioifdm:bc_hmean`.

**Comment by opeeters** [comment]
We don't have forecasts for Black Carbon. Let's drop Black Carbon from the detail-view for the time-being and only add the BelAQI.

**Comment by opeeters** [comment]
All parameters (besides the index) are listed twice now in `view in detail`:

<img width="317" alt="Screenshot 2020-11-20 at 12 12 52" src="https://user-images.githubusercontent.com/323719/99794290-399ad000-2b2a-11eb-8c9b-5ad32d16f538.png">

**Comment by opeeters** [comment]
Additionally, `app-value-display` (in the case of the index this should be the text `fairly good`, etc.) is missing for the index:

<img width="318" alt="Screenshot 2020-11-20 at 12 22 01" src="https://user-images.githubusercontent.com/323719/99794957-49ff7a80-2b2b-11eb-95c1-b53a4b443f56.png">

This might be related to the the double display of all other parameter, since one of the two entries of the other parameters has the same problem.

**Comment by opeeters** [comment]
Looking good.
But... when going first to detail BelAQI > back to selection options detail view > e.g. PM2.5
the `app-value-display` is not updated with the value for PM2.5

**Comment by janschulte** [comment]
Should be fixed, also the not working translations.
