### ISSUE TITLE
implement notifications

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#242]
<img width="432" alt="Screenshot 2020-10-29 at 13 58 06" src="https://user-images.githubusercontent.com/323719/97576793-e6cc6d80-19ee-11eb-81f1-fd9f79355972.png">

When an official push-notification has been pushed, the exclamation mark icon should appear. Clicking on the icon should open a pop-up where the user can read the message again.

**Comment by opeeters** [comment]
channels:
- belair_nl
- belair_fr
- belair_de
- belair_en

Or is there a new i18n for FCM?

**Comment by janschulte** [comment]
I don't find the exclamation mark icon in the code base. Could you please provide this. I don't know accurate coloring, font and position of the icon in the UI.

**Comment by opeeters** [comment]
I added an svg which can be used as icon. Just add it somewhere over the index-wheel. I will fix the exact position later..

**Comment by opeeters** [comment]
Looking good.
One thing though, when deactivating the notification in the settings, the notification exclamation mark remains active on the landing tab..

**Comment by janschulte** [comment]
Implemented with the last commit.
