### ISSUE TITLE
Central alignment app-time-line-list

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#244]
See commits on 12/10 and 20/10 on the v2-upgrade branch. There were multiple alignment issues of all the elements, but not all problems have been resolved. 

See e.g. screenshots on Samsung A50:
- slightly off center but still OK:
![Screenshot_20201120-124255_BelAir_v2](https://user-images.githubusercontent.com/323719/99797251-30f8c880-2b2f-11eb-9f0b-6ba7bf8d3580.jpg)

- more problematic:
![Screenshot_20201120-124245_BelAir_v2](https://user-images.githubusercontent.com/323719/99797294-4968e300-2b2f-11eb-8dc8-5bce166b55d4.jpg)

**Comment by bieblebrox** [comment]
Can you confirm this is okay now? @opeeters

**Comment by opeeters** [comment]
On smartphones in portrait it looks perfect!
On a tablet the distribution of the elements could all be in view and not like this:

![localhost_4200_main(iPad Pro)](https://user-images.githubusercontent.com/323719/115580675-9c55ea80-a2c7-11eb-97a7-667266341392.png)

**Comment by bieblebrox** [comment]
View updated for tablets as well
