### ISSUE TITLE
register for the official notifications by default

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#249]
See e02ab64 
The default setting for official notifications should be subscribe = true. 
Please review commit e02ab64. I tested the notification. They do arrive and the subscribe/unsubscribe also seems to work..

We will include the functionality of subscribing to a anonymised personal topic (cf #168) at a later stage.

**Comment by janschulte** [comment]
I just have a couple of questions about this:

The UI currently contains two types of notification: official and automated. Will automated be the same functionality as #168. Or is this something different? For release 1.7.5 we wopuld then only have the official notifications?

You wrote, that the notifications are already working. Did you encounter any problems or should I jsut provide a review of the code?

**Comment by opeeters** [comment]
The user has to be asked for consent to receive notification. Default state of `false` is hence the better option.
