### ISSUE TITLE
incorrect screen organisation after location input

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#250]
Steps to reproduce:
- open the app and add a location manually during the onboarding or remove all the locations in the settings and enter a location manually after going to the landing tab.

Result:
You are taken to the location just configured, but the view in detail slide is positioned to high on the landing page (see below).

![Screenshot_20201207-145953_BelAir_v2](https://user-images.githubusercontent.com/323719/101367090-0ab08800-38a6-11eb-9ca0-6261207e7368.jpg)

**Comment by bieblebrox** [comment]
Fixed
