### ISSUE TITLE
Wrong background colour landing tab after entering (new) location via settings

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#251]
When entering a (new) location via the settings-tab and returning to the landing page by closing the settings-tab, often, the background colour of the landing tab does not correspond with the `current` value:

![Screenshot_20201207-150138_BelAir_v2](https://user-images.githubusercontent.com/323719/101369039-2321a200-38a8-11eb-823e-a4aaf8a9ab20.jpg)

**Comment by janschulte** [comment]
I rearranged the background image component and with that it should  be fixed now
