### ISSUE TITLE
Error-View in case of unreachable time_app_json

### ISSUE THREAD

**Issue by janschulte** [irceline/aq-mobile-be#252]
Currently https://www.irceline.be/air/time_app_json.php isn't reachable and the app isn't usable in this case. I think a default hint for the user is needed. Do you have a mockup or something for this case?

**Comment by opeeters** [comment]
Let's start simple. When https://www.irceline.be/air/time_app_json.php is not responding, a pop-up informs the user that the servers are not reachable.

A distinction could be made between servers not responding versus a device having no network connectivity (cf alerts in BelAir v1).

**Comment by janschulte** [comment]
Implemented with last commit
