### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#253]

**Comment by opeeters** [comment]
There currently is a compilation error on the 52n-v2-upgrade branch:
```
ERROR in src/app/v2/components/background/background.component.ts:6:10 - error TS2305: Module '"../../common/enums"' has no exported member 'valueDateToString'.

6 import { valueDateToString } from '../../common/enums';
```

@janschulte you probably forgot to commit your local changes to common/enums.ts, no?

**Comment by janschulte** [comment]
Sorry for that, I forget to cleanup completly after testing the background image behaviour. Is fixed now.
