### ISSUE TITLE
Edit tab not opening correctly

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#255]
On the current `52n-v2-upgrade` branch, after selecting one of preset locations of using the location service, clicking `edit` (either during the onboarding or when all locations are removed and you add a location via the landing tab), the edit tab comes up incomplete:

![Screenshot_20201218-183705_BelAir_v2](https://user-images.githubusercontent.com/323719/102672951-970a5700-4192-11eb-86c1-24d42929586a.jpg)

This is not the case on the current `v2-upgrade` branch.

**Comment by janschulte** [comment]
Fixed with last commit

**Comment by opeeters** [comment]
Thanks!
