### ISSUE TITLE
i18n of helgoland viewer

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#26]
when being forwarded to the diagram page, the viewer should be opened in the language set via the language settings

**Comment by janschulte** [comment]
Is fixed with: be4d59b398cdc0d27014dfda06311176a8e5d521

**Comment by opeeters** [comment]
Label "time" on x-axis diagram is not translated. Rest seems fine.

**Comment by janschulte** [comment]
Oh, you right. Sorry. Or should I remove it completely, because it's obvious.

**Comment by opeeters** [comment]
OK, more space for the rest

**Comment by janschulte** [comment]
Done with: cb4079e7a00f3bff099edd1ccf1a1af185ce597a

**Comment by opeeters** [comment]
seems to be fine after `npm install`. Closing issue..
