### ISSUE TITLE
activated toggles are more difficult to see than non-activated

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#263]
Take e.g. this situation:
![Screenshot_20210406-112548_BelAir_v2](https://user-images.githubusercontent.com/323719/113690520-cacea580-96cb-11eb-8357-6498ea640a56.jpg)

With a green background it is more difficult to see the activated toggle than the non-activated one.

Proposition: follow the styling of the click model
<img width="346" alt="Screen Shot 2021-04-06 at 11 27 30" src="https://user-images.githubusercontent.com/323719/113690838-226d1100-96cc-11eb-8663-282de77134ab.png">

**Comment by bieblebrox** [comment]
Using same slider on iOS & Android now

**Comment by opeeters** [comment]
Apparently on iOS it is difficult to change the state of these toggles. Maybe the click action (tap to change state) is disabled by default on iOS? Apparently you really have to pull laterally to change the state.

**Comment by opeeters** [comment]
Additionally, we should change the background of the toggle itself from transparant to white in the non-active state:

![Screenshot_20210427-102755_BelAir_v2](https://user-images.githubusercontent.com/323719/116212573-3f35bb00-a745-11eb-8908-65cb8c133896.jpg)

In the active state there is not enough contrast to the background in the default mode for certain index colours. What are the options? Add a thin light-grey border? Add a semi-transparant light background to class `notification-settings` (the <div> containing these settings)?

**Comment by opeeters** [comment]
E.g. like this:

<img width="331" alt="Screen Shot 2021-04-27 at 10 51 15" src="https://user-images.githubusercontent.com/323719/116214021-97b98800-a746-11eb-8026-5ce52a50d2df.png">

Not perfect, but better, no?
