### ISSUE TITLE
add animation to landing tab when data is loading

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#264]
When launching the app for the first time on a given day, loading data from the servers can take a bit longer leaving the user look at this:

![Screenshot_20210406-112232_BelAir_v2](https://user-images.githubusercontent.com/323719/113691444-b5a64680-96cc-11eb-9212-b31f3f8eb3a9.jpg)

Let's add an animation for the time the data ia being loaded, e.g. a pulsating (bigger<>smaller or varying the opacity):
![Screenshot_20210406-114050_BelAir_v2](https://user-images.githubusercontent.com/323719/113691767-1766b080-96cd-11eb-8b94-18885b26e429.jpg)

in the center of the index circle

**Comment by bieblebrox** [comment]
done
