### ISSUE TITLE
dynamically resize font of the circle chart text

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#266]
In some cases the circle chart text (e.g. NL - `middelmatig`) is uncomfortably big on some screens (in this case a Samsung A50). We should resize this text base on the number of characters of the specific translation of the index label.

![Screenshot_20210414-201912_BelAir_v2](https://user-images.githubusercontent.com/323719/115024307-33820300-9ec0-11eb-908f-75a28d379f17.jpg)

**Comment by opeeters** [comment]
fixed with 4e246739c73cb44369384a3548c63d141489ade0

**Comment by opeeters** [comment]
I'm reopening this, because there are several over cases which are problematic (e.g. `ondermaats` and others). I was think more of a solution which adapts to the screen width based on the number of characters.

**Comment by bieblebrox** [comment]
https://github.com/irceline/aq-mobile-be/commit/a2001333129a55473937cdd6780ba473d211e9e1
