### ISSUE TITLE
change navigation app

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#27]
Instead of a folded navigation tab, have a bar with icons on the top of each page

aligned left:
```
<ion-icon name="home">Home</ion-icon>
<ion-icon name="map">Map</ion-icon>
<ion-icon name="stats">Diagram</ion-icon>
```

aligned right:
```
<ion-icon name="refresh">Refresh</ion-icon>
<ion-icon name="settings">Settings</ion-icon>
```

With language aware text appearing on bigger screens.

**Comment by janschulte** [comment]
added with: 6506632d4fdeb7e3af4d0bcb25092384b2fe9442
