### ISSUE TITLE
Onboarding: when keyboard is expanded, elements cover each other

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#271]
When the keyboard of the device is expanded during the onboarding (location selection), elements are interfering with each other (at least the `save` should not be covered):

![Screenshot_20210421-204733_BelAir_v2](https://user-images.githubusercontent.com/323719/115610588-5b6ecd80-a2e9-11eb-989f-1b9ce8dc3007.jpg)

**Comment by bieblebrox** [comment]
should be fixed with keyboard avoiding mode commit - is it still reproducible on the latest version?

**Comment by opeeters** [comment]
Fine, thanks!
