### ISSUE TITLE
wrong styling and values longterm page

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#273]
On Android and iOS:

![20210428_194338](https://user-images.githubusercontent.com/323719/116475015-8755fa00-a879-11eb-8e54-1d100906b7da.jpg)

Wrong value and styling (cf click model). The value should be the value of the last year (in this case value: 48). The font color should correspond with the relevant index color. On iOS the border thickness should also be reduced.

**Comment by bieblebrox** [comment]
![File (1)](https://user-images.githubusercontent.com/53826760/116555972-3daef300-a8fd-11eb-95d5-0cb97813d6e5.jpg)

screenshot from latest testflight build

https://github.com/irceline/aq-mobile-be/commit/42b3a50f6584536128b199199af07f319b002552

**Comment by bieblebrox** [comment]
![Screenshot_20210430-124815_BelAir_v2](https://user-images.githubusercontent.com/53826760/116685352-7bba1e80-a9b2-11eb-9c47-fbbdfc48d8cb.jpg)

This is on latest build, only thing is that the bar chart colors seem to be different from the text (eg fairly good, shows red bar chart)

**Comment by janschulte** [comment]
Until now the big numbers are the current modelled values to every shown phenomenon. Now you want to change it to the value of the last year? I don't understand, why to show the value of the last year 3 times? If i am right, i would be much better to refactor the component, than overriding one value as happend...

**Comment by janschulte** [comment]
Hopefully everything is adjusted as whished.

**Comment by opeeters** [comment]
Looking good! Thanks @janschulte
Some minor things in the browser version at least. I might come back to you if I cannot manage myself ;-)

**Comment by opeeters** [comment]
![Uploading Screenshot_20210430-164019_BelAir_v2.jpg…]()

**Comment by opeeters** [comment]
> ould be much better to refactor the component, than overriding one value as happend...

**Comment by opeeters** [comment]
> Until now the big numbers are the current modelled values to every shown phenomenon. Now you want to change it to the value of the last year? I don't understand, why to show the value of the last year 3 times? If i am right, i would be much better to refactor the component, than overriding one value as happend...

**Comment by opeeters** [comment]
I had another look at the click-model.. I was wrong.. different in the design they put the EU-threshold above the graph:

<img width="373" alt="Screen Shot 2021-04-30 at 16 56 30" src="https://user-images.githubusercontent.com/323719/116713708-57236e00-a9d5-11eb-9e22-39dad8596de5.png">

**Comment by opeeters** [comment]
After some internal discussion we decided to also add the WHO guideline values as text to the long-term tab:

<img width="458" alt="Screen Shot 2021-04-30 at 23 41 25" src="https://user-images.githubusercontent.com/323719/116757109-bdc47e00-aa0d-11eb-9ed4-803478377f43.png">

@janschulte please check if my implementation was OK. Could you please still add the latest annual BelAQI to the `view in detail` pull-tab (cf click-model, but than as evaluation text - e.g. `very good` - and not a concentration):

<img width="372" alt="Screen Shot 2021-04-30 at 23 35 29" src="https://user-images.githubusercontent.com/323719/116757920-5dced700-aa0f-11eb-800d-84719def8de4.png">

**Comment by opeeters** [comment]
One more thing, the horizontal lines of the EU/WHO-limits in the graph are not correctly drawn. See e.g. (the red line indicates where the blue dashed line should be - see EU/WHO limit values):

<img width="458" alt="Screen Shot 2021-04-30 at 23 41 25" src="https://user-images.githubusercontent.com/323719/116758409-3c221f80-aa10-11eb-9604-ca4f021832cb.png">

**Comment by janschulte** [comment]
> @janschulte please check if my implementation was OK. Could you please still add the latest annual BelAQI to the `view in detail` pull-tab (cf click-model, but than as evaluation text - e.g. `very good` - and not a concentration):

Looks good so far. I have done some refatoring in  long-tem-data service to remove unused request for current values.

Additionally I add the adjustment to the details view with 2e2b86cb25d211272e44117b89d6b96e686a6bd7

**Comment by janschulte** [comment]
I hopefully doesn't miss anything in this Issue, otherwise please inform me again. I change the assigne to @bieblebrox for the threshold markers

**Comment by bieblebrox** [comment]
https://github.com/irceline/aq-mobile-be/commit/74804f001b4636ad9c5f82b749dc0f5479a50253
