### ISSUE TITLE
example values in on info tab gone missing

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#274]
We used to have 4 values here (O3, NO2, PM10 and PM2.5 - see older versions) - both on Android and iOS: 
![20210428_194325](https://user-images.githubusercontent.com/323719/116475368-0c411380-a87a-11eb-97ea-a12fcfbc39ae.jpg)

**Comment by bieblebrox** [comment]
![File (2)](https://user-images.githubusercontent.com/53826760/116556424-b7df7780-a8fd-11eb-81cc-eb44419691da.jpg)
