### ISSUE TITLE
Cannot click "view our long-term calculation" on iOS

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#275]
Impossible to click "view our long-term calculation" on iOS (iPhone 11 in this case) - you cannot keep pulling tab up and click at the same time. When you pull the "view our long-term calculation" in view, it disappears off-screen as soon as you let go.

![20210428_194310 (1)](https://user-images.githubusercontent.com/323719/116475683-7a85d600-a87a-11eb-98d2-e8498a1444d2.jpg)

**Comment by bieblebrox** [comment]
https://user-images.githubusercontent.com/53826760/116559796-13f7cb00-a901-11eb-95c6-0930ac84299f.mp4

Screen recording from iPhone 11 iOS 14 on latest build (iOS)
