### ISSUE TITLE
add BelAQI to longterm-info screen and set colour O3 to grey

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#277]
The click-model also has a graph with the BelAQI index for annual means. This data was not yet available, but is now (belaqi_anmean_2015 through to belaqi_anmean_2019). Please add a BelAQI graph.

Reorder the graphs, top to bottom:
- BelAQI
- NO2
- PM2.5
- PM10
- O3

Additionally, the bars in the bar chart of only O3 should be grey (as long als the values are still readable the shade of grey is fine) and not coloured according to the index colours as is currently the case.

**Comment by janschulte** [comment]
I am confused. There is a WMS https://geo.irceline.be/rioifdm/belaqi_anmean_2017/wms?service=WMS&request=GetCapabilities but only with layers belaqi_anmean_2018 and belaqi_anmean_2019.

Same for:
- https://geo.irceline.be/rioifdm/belaqi_anmean_2016/wms?service=WMS&request=GetCapabilities
- https://geo.irceline.be/rioifdm/belaqi_anmean_2015/wms?service=WMS&request=GetCapabilities

Wrong deployments or where should I find the older layers?

**Comment by janschulte** [comment]
And an other point are the barcharts. Currently the barchart base on the µg/m³ Scaling. For the belaqi I have to adjust the scaling to the index values between 1 and 10? Could you maybe give me a screenshot of the click-model?

**Comment by opeeters** [comment]
<img width="376" alt="Screen Shot 2021-04-30 at 12 39 46" src="https://user-images.githubusercontent.com/323719/116684576-65f82980-a9b1-11eb-9171-1c665685863e.png">

**Comment by opeeters** [comment]
> I am confused. There is a WMS https://geo.irceline.be/rioifdm/belaqi_anmean_2017/wms?service=WMS&request=GetCapabilities but only with layers belaqi_anmean_2018 and belaqi_anmean_2019.
> 
> Same for:
> 
> * https://geo.irceline.be/rioifdm/belaqi_anmean_2016/wms?service=WMS&request=GetCapabilities
> * https://geo.irceline.be/rioifdm/belaqi_anmean_2015/wms?service=WMS&request=GetCapabilities
> 
> Wrong deployments or where should I find the older layers?

See: https://github.com/irceline/aq-mobile-be/issues/277#issuecomment-829985015

**Comment by janschulte** [comment]
Hopefully everything is adjusted as whished.

**Comment by opeeters** [comment]
All is well, thanks everyone!
