### ISSUE TITLE
Language change in menu does not change language on openingspage

### ISSUE THREAD

**Issue by ffierens** [irceline/aq-mobile-be#280]
Choosing an other language in menu does not change the language on first screen.
version 1.7.9
galaxy A50

**Comment by opeeters** [comment]
You mean that some elements (e.g. the `continue` button) are not translated until you go to the next slide? The graphics still need to get a i18n version. I will add this a.s.ap.

**Comment by ffierens** [comment]
When data from the previous days are missing (due to e.g. technical issues) a grey box indicating "not available or NA", "niet beschikbaar or NB", "pas disponible or PD" could (should?) be used. Screenshot = example from last weekend (5/6 June 2021). Same remark when forecasts are missing.

![Screenshot_20210605-103553_BelAir_v2](https://user-images.githubusercontent.com/12494775/121179730-5695b700-c860-11eb-9f01-30725f000f96.jpg)

**Comment by opeeters** [comment]
solved with:
20f4624bf9e4fa5ebe39d69364036769240d8f87 
8402a29ee6b9fefebb18aedce3d26b8a51206911 
0cd191080e3f1bf889caabb5871a4b7b2b898f55
