### ISSUE TITLE
version 1.8.0 not showing intro screen

### ISSUE THREAD

**Issue by ffierens** [irceline/aq-mobile-be#288]
Version 1.8.0 opens with a white screen. This should be the page with the logo's from irceline and the regional partners.
issue on android 11, Galaxy A50

**Comment by bieblebrox** [comment]
![Screenshot_20210622-123111_BelAir_v2](https://user-images.githubusercontent.com/53826760/122909821-de49ee00-d355-11eb-89a9-197317e3013c.jpg)
Do you mean this splash screen?

**Comment by ffierens** [comment]
yes

**Comment by opeeters** [comment]
The app probably was opened and set to hc-mode before, no?

**Comment by ffierens** [comment]
Yes, this was indeed the case.
