### ISSUE TITLE
revamp user location configuration

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#29]
1) add link to "create new location" as last element on "show current locations" page, so even if no locations have been configured (same as on "create new location" page)
2) add button to clear text of result geosearch (text can be rather long and it's is not very userfriendly having to clear the text manually), maybe add suggestions for labels (e.g. "Home", "Work", "School")
3) make icon of location search result drag and drop (e.g. if you searched on Gent and you want to move the location to your area of the city).
4) fix bug: when adding location via "create new location" and changing label directly, your change is not retained
5) add scroll on side of page "location list" (probably add `<div>` around `<ion-card class"card card-md">` with `overflow-y: scroll;`)
6) make not only name of location editable, but also location itself (see point 3)

**Comment by janschulte** [comment]
To 2: is done with: 31e3d55059c3564822756dd0bcc5207cbc139c35

To 4: You must confirm the creation on the button. After that you are only able to edit the label on the list view or delete the location. 

To 5: I don't see any problems with the scrolling. Only when you try to scroll over the map snippets you just zoom in or out. I can disable the zooming on the map snippets, then the touch event can be used to scroll. 

To 6: For the workflow it isn't that easy to support also editability of the location in the list view. How should that happen (see scrolling on map, how should that be confirmed?). Therefore I suggest a new view to edit the location?

**Comment by opeeters** [comment]
To 4: This is not very convenient. Either disable "change the location label" and remove this text, or make labels editable right away. I prefer the latter. There was something missing in: 31e3d55. Added with: b223cec
To 5: I disabled `dragging`, with: ff1f3ae
This seems to work OK
To 6: let's revisit this later..

**Comment by janschulte** [comment]
As far as I see the first 5 points are implemented now.

**Comment by opeeters** [comment]
To 1: I think we have a misunderstanding. You added a "create new location" button as a slide in belaqi-user-location-slider. I meant adding a button in the settings as last element in the pop-up behind "Show current locations".

The rest is OK
We'll get back to 3 & 6

**Comment by janschulte** [comment]
Ok, sorry. I add now a button to the user created locations list. Hopefully this is right.

Should i remove the button from the slider? Because it also produces the Issue: https://github.com/irceline/aq-mobile-be/issues/36

Done in 9115aa35d769b8dff71b188a91ae537502db86f7
