### ISSUE TITLE
Arrow language selection not working

### ISSUE THREAD

**Issue by ffierens** [irceline/aq-mobile-be#290]
The arrow for language selection does not work (clicking language text does).
![image](https://user-images.githubusercontent.com/12494775/122881633-a8980b80-d33b-11eb-8fcf-0ecfe41f30e2.png)

app version 1.8.0, android 11, Samsung galaxy A50

**Comment by opeeters** [comment]
Tested on an A50 with android 11. All works as expected. There is a slight lag on slower devices like the A50. When touching the screen too briefly, the pop-up is not opened. On faster devices (tested in a S20) this never happens. Solution: touch the screen a little longer and the pop-up will appear, also on an A50.

**Comment by ffierens** [comment]
clicking just left or just right of the arrow works, but not on the arrow.

**Comment by bieblebrox** [comment]
fixed on 1.8.1
