### ISSUE TITLE
make limit geosearch configurable in the settings.json

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#3]
see:
* https://github.com/smeijer/leaflet-geosearch/issues/81

so, e.g. in 
L.GeoSearch/src/js/l.geosearch.provider.openstreetmap.js
change code to:
```js
GetServiceUrl: function (qry) {
        var parameters = L.Util.extend({
            q: qry,
            countrycodes: 'be',
            format: 'json'
        }, this.options);

        return (location.protocol === 'https:' ? 'https:' : 'http:')
            + '//nominatim.openstreetmap.org/search'
            + L.Util.getParamString(parameters);
    },
```
This configuration option could best be added to [Helgoland](https://github.com/52North/helgoland)

**Comment by janschulte** [comment]
Implemented with 67383ee2ba52780a9b323be5f4699d1a47c1fc8e
Configuration can be adjusted with `geoSearchContryCodes`
