### ISSUE TITLE
add timeseries from `nearest station` to diagram

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#33]
By default, add the five timeseries from nearest station to `diagram` page.

If location is not available, take top configured location.

If no location is configured, display message "No timeseries selected!" as is the case currently.

That message should be changed to something like:
```
Enable your location service to find the nearest measuring station.

Alternatively configure a location in your app settings: 
<link to `create new location`>

or select a timeseries: 
<map>
```

**Comment by opeeters** [comment]
Yes, by default five timeseries from current location. Follow the state the start page.
Not entirely sure how add/remove of custom timeseries should work. Maybe indeed option to remove individual timeseries + a button to reset to default.
I love your idea to click on station in the map and get a diagram (default today/yesterday) with the option to add to diagram! This would be great upstream too.

**Comment by janschulte** [comment]
Done with the last commits.
