### ISSUE TITLE
after update app, language setting is changed back to EN

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#34]
If you change language to something else than EN, the language is changed back to EN after every update. The language setting, configured locations, selected timeseries should be remembered.

**Comment by janschulte** [comment]
All mentioned parameter will be stored by the [ionic storage](https://ionicframework.com/docs/storage/).
Currently I couldn't test if it also works in the update process of the playstore. We should observe this.

Done with: 29d785c9efa641170a2b4c5b8b61172d8af4950b

**Comment by opeeters** [comment]
OK, I will close issue and get back to it should this not be sufficient.
