### ISSUE TITLE
No way back from create-new-location-slide in belaqi-user-location-slider 

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#36]
On the start page, in the belaqi-user-location-slider, when on create-new-location-slide, it is not possible to slide back. Build version 0.4.6. Only option is to kill the app and not going to that slide. This might also be related to production build.

**Comment by berntholer** [comment]
I can confirm this issue is present since 0.4.5. In 0.4.6 I at least get the option to create a new location, but no possibility to return to other locations or do anything else, the only option is to kill the app like @opeeters  says.

**Comment by janschulte** [comment]
Auto height for the slider with: 5fb14680966903a93f8be30103bb363a6859b934
