### ISSUE TITLE
legend becomes unreadable in diagram

### ISSUE THREAD

**Issue by berntholer** [irceline/aq-mobile-be#38]
when 5 or more pollutants are chosen the legend in the diagram becomes unclear. maybe limit the number of pollutants or summarize in another way?

![screenshot_20180916-093657](https://user-images.githubusercontent.com/24441447/45612117-3dba9700-ba62-11e8-960a-558a048e6007.png)

**Comment by janschulte** [comment]
The legend is scrollable now...
