### ISSUE TITLE
negative concentrations are shown 

### ISSUE THREAD

**Issue by berntholer** [irceline/aq-mobile-be#39]
sometimes measurements show negative concentrations (i.e. O3), in this case no concentrations should be shown.

![screenshot_20180916-093345](https://user-images.githubusercontent.com/24441447/45612155-69d61800-ba62-11e8-95e3-3116ecc9b110.png)

**Comment by opeeters** [comment]
Will correct SOS-data for this. Was this today @ 9h00?

**Comment by d-roet** [comment]
this issue seems to be resolved?

**Comment by opeeters** [comment]
No, not yet. But we are working on it in conjunction with other REST-api related issues (e.g. stations which have been closed, translation of pollutants)
