### ISSUE TITLE
implement config option "clusterStations"

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#4]
adding: 
```json
"clusterStations": false 
```
to `setting.json` has no effect

**Comment by janschulte** [comment]
Added with 8d89e57e66c8b951aac9a534f8cd903996aa1de8

Can be configured with `clusterStationsOnMap` in [settings.json](https://github.com/irceline/aq-mobile-be/blob/master/src/assets/settings.json) now
