### ISSUE TITLE
diagnostic notifications keep appearing

### ISSUE THREAD

**Issue by berntholer** [irceline/aq-mobile-be#40]
production build 0.4.6 still shows these notifications

![image](https://user-images.githubusercontent.com/24441447/45612183-86725000-ba62-11e8-94b7-230d5fde5c65.png)

**Comment by opeeters** [comment]
which version of the app?
See `settings` > `about the app` 
(if this section absent, please update and see if problem persists)

**Comment by berntholer** [comment]
as stated in the beginning of my post .. 0.4.6

**Comment by opeeters** [comment]
:-) sorry, I need another coffee
That is a production build.
@janschulte we need to improve task management. I got complaint elsewhere that app drains battery when left open in background.

**Comment by janschulte** [comment]
Added better and internationalized information about the background service with: 57f8f078e3abca7cb996a11dffb39c1d479c294b
