### ISSUE TITLE
receiving notification for an unkown location

### ISSUE THREAD

**Issue by berntholer** [irceline/aq-mobile-be#44]
in production version `0.4.6` the notification for location "De Herk, Bertem" is still present, although the user did not add this location ;)

![screenshot_20180917-101850](https://user-images.githubusercontent.com/24441447/45613114-832c9380-ba65-11e8-839c-094543c0fe02.png)

**Comment by opeeters** [comment]
This is the default location when no location is set. Please revise @janschulte
