### ISSUE TITLE
returning from locations screens not intuitive

### ISSUE THREAD

**Issue by berntholer** [irceline/aq-mobile-be#48]
when sliding to the last locations screen, where you can make a new one, the only way to go back to already defined locations (=swipe left) is if you swipe **exactly** in the white rectangle. when you swipe below, i.e. gray area it doesn't work ...

tested under version `0.4.9`

![image](https://user-images.githubusercontent.com/24441447/46026514-df3d8a80-c0eb-11e8-8fba-4bb8b469df2c.png)

**Comment by opeeters** [comment]
@berntholer Is this sufficient in 0.5.0?

**Comment by opeeters** [comment]
@janschulte do you maybe have a better solution. Best would be to have the height of the slide adapt to screen size, but I did not manage to find a robust solution with ionic.

**Comment by janschulte** [comment]
Done with 2ef6bc1d9d8a6310224f838e0af2e638056bf733
