### ISSUE TITLE
change overlays dynamically with change selection phenomenon

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#5]
So for instance is `Nitrogen dioxide` is selected, `pm10_hmean_1x1` should be removed and `no2_hmean_1x1`, etc.

**Comment by janschulte** [comment]
Implemented in be687a8bc7563df56a3996b9895988a8262bb690
With the configuration `phenomenonLayerMapping`  you can add a phenomenon ID to WMS Layer mapping. Per Phenomenon ID an Array of layers is defined. A layer consists of: 

- `label` - visible in the map layer control
- `visible` - default config if the layer is directly visible
- `baseUrl` - wms service url
- `layer` - layer options for the request (see also http://leafletjs.com/reference-1.3.0.html#tilelayer-wms)
