### ISSUE TITLE
select station as nearest only when lastValue is within the last 24 hours

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#50]
Create for instance a location "Hasselt". The nearest station found will be 42N045 - HASSELT. This station was closed down more than a year ago. As a general check I would propose only selecting a station as nearest if lastValue is less than 24 hours ago (some margin since a station can be down due to maintenance). If lastValue is not more recent or the same than "lastupdate" from http://www.irceline.be/air/time_app_json.php the background of the pollutant-button should be white.

**Comment by janschulte** [comment]
Done with d1764fbaaead1fabc2677732c454364795811583
