### ISSUE TITLE
change state of "current location" toggle button bug

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#51]
Steps to reproduce:
- open app with "current location" deactivated
- go to "location list" and activate "current location"
- go back to start page
No more data
Maps and diagram data comes through normally

**Comment by janschulte** [comment]
I tried your way, but i don't understand what you mean with no more data. I see an other problem, when you add or remove some location, the slider length on the start view is changed regarding to the configured locations. So it normally will be the case, that the slider is now on a wrong position. I can jump always to the first slider element, when the user changes some of it's locations. Maybe this also fix your described bug...

**Comment by opeeters** [comment]
with no data I mean no index wheel appearing

**Comment by opeeters** [comment]
![screenshot_20181012-104432](https://user-images.githubusercontent.com/323719/46858621-f975a900-ce0b-11e8-8495-f3a860b4d0c6.png)

In this case even when localisation service is active, the "The geolocation is disabled" message is displayed.

**Comment by opeeters** [comment]
Also, when "current location" is activated again, there is an index wheel again, but the "The geolocation is disabled" message remains, even when the service is active.

**Comment by janschulte** [comment]
I did some changes, which should improve the complete handling with the the 'current location' and the enabled/disabled device location. Done with: a184b80d5e79c2d31d46228bd61ada0acdbe15d8

**Comment by opeeters** [comment]
If you open app now with `current location` deactivated, you get no index wheel even when you have locations configured. Also see #56

**Comment by janschulte** [comment]
See comment in the other issue: https://github.com/irceline/aq-mobile-be/issues/56#issuecomment-430614067
