### ISSUE TITLE
limit return OSM nominatim

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#53]
the output from the reverse geosearch via OSM nominatim is a bit excessive (e.g. address, quarter, city, region, country). Is it possible to limit this return? E.g. to address + city.

**Comment by janschulte** [comment]
Done with: 5add67941b3182b4dba1252dc4c60a79b2c103c8

**Comment by opeeters** [comment]
I see no change in the way the reverse geosearch works. The return looks unchanged

**Comment by janschulte** [comment]
Should be fixed now: d4f68f7e88f9641f97de24468c4eb455e4cf05eb

**Comment by opeeters** [comment]
perfect!
