### ISSUE TITLE
make index value in wheel correspond with 'now' in graph

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#54]
E.g. here:
![screenshot_20181016-111921](https://user-images.githubusercontent.com/323719/47006246-c564f580-d135-11e8-977f-128fcc28a225.png)
In the wheel the value is 4. In the graph it is 5. In the graph the 6 index values (incl. 'now') should be taken from the belaqi index map and hence the value should be the same.

**Comment by janschulte** [comment]
As discussed internally, i added pm25 to calculate the belaqi index on app side: d03b176d2b8b36968d822c94af0b9188ea9a3e1f

**Comment by opeeters** [comment]
This clearly performs better now. I will close the issue for the time being
