### ISSUE TITLE
Refresh button is not refreshing everything in the app

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#55]
Refresh button is not refreshing everything in the app.
E.g. change language in settings > refresh : text in index wheel will remain in previously set language
Or open app and wait an hour > refresh : content + last update is not refreshed
It is necessary to close app and launch it again in both cases

**Comment by janschulte** [comment]
1736d82d45c4206e662a694bb42bec1445313504 fixes language in wheel
b0bbcfb2a841eabd436047a0adb4e59d5502327f add refresh to slide with wheel, graph and nearest stations
