### ISSUE TITLE
When no location is configured no index wheel is shown

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#56]
When no location is configured no index wheel is shown even when location service is activated and `current location` is activated. Even when you add a location no index wheel is shown. You first have to deactivate `current location` for the index wheel of the configured location is shown.

**Comment by janschulte** [comment]
I do a small adjustment with 9a6dcbc912f0d35e498ceedff6136aeed9a54346
If this doesn't help, could you also clear the app data, because there were some changes in the locations structure with the last commits, maybe this also has in affect on your issue.

**Comment by opeeters** [comment]
I will compile and get back to you..

**Comment by opeeters** [comment]
There still is the following bug:
- if you install app and you don't configure a location, no index wheel is shown even when you activate `current location` and you have the location service of your device enabled. This remains the case when you close the app. Also when you add a location (via geosearch), no index wheel, graph + nearest station is shown. See:
![screenshot_20181017-151523](https://user-images.githubusercontent.com/323719/47088808-a0e54800-d21f-11e8-9942-e64499160f4b.png)

Restarting the app does not solve the problem.

Only solution is to disable `current location`. Than at least the configured location is correctly used for wheel, graph and nearest station.

**Comment by opeeters** [comment]
I did another compile with 1736d82 and b0bbcfb..
Now the location seems to work correctly.
