### ISSUE TITLE
colour station when latest measurement is not available

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#57]
In the old jsclient there was a setting to have stations that do not have data for the latest hour be greyed out. I think it was:
```
"ignoreAfterDuration": "moment.duration(0.5, 'h')",
```
Is there something similar in the helgoland toolbox?

**Comment by janschulte** [comment]
Currently not, but I will add this to the next version of the toolbox.

**Comment by opeeters** [comment]
If next version of the toolbox is coming after end of October we need an ad hoc solution for this in the app

**Comment by janschulte** [comment]
Done with: bc387d555f1fe7897e04eda928fac78f1434c8b4
Currently can be configured here: https://github.com/irceline/aq-mobile-be/blob/master/src/pages/map/map.ts#L63

Should it be configurable in settings.json?

**Comment by opeeters** [comment]
yes please, add it to settings.json

**Comment by janschulte** [comment]
Done with: c3643356604547200d238bcc2c3141cef15f533a
