### ISSUE TITLE
i18n of phenomena names

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#58]
The REST-api has i18n (eng, dut, ger & fre) now. See e.g.:
* http://geo.irceline.be/sos/api/v1/phenomena?locale=dut
This is not yet reflected in the app in elements where the name is taken from REST-api output.

**Comment by opeeters** [comment]
related to #37

**Comment by d-roet** [comment]
I strongly recommend using all lowercase for pollutant names (especially in Dutch). Also pollutant seems to not have a dutch translation yet e.g. `...{"id":"391","label":"Black Carbon"}..`

@opeeters : I am always willing to help out with translations and such ...

**Comment by opeeters** [comment]
OK, I changed this for `dut`, `eng` and `fre`. For `ger` this would not work.

**Comment by janschulte** [comment]
@opeeters, is it a big effort for you to adjust the language codes to the ones used in the client (en, nl, de, fr). The client works with this ones. Otherwise I can adjust it in the client, your choice. ;)

**Comment by opeeters** [comment]
ah, I thought that the SOS would only understand the 3 letter codes.. I will change the codes in the database. I prefer the shorter version.
