### ISSUE TITLE
selected nearest station lists value of several hours ago

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#59]
See here:
![screenshot_20181017-145355](https://user-images.githubusercontent.com/323719/47087619-c3c22d00-d21c-11e8-8c4c-52fc0bb3dffc.png)
The closest BC station in this case is indeed Woluwe, but this station did not have any valid data in the morning. The last valid value (`1,2` @ 06h00) is listed at 14h00... Only values from the latest hour should be listed in the nearest station banner..

**Comment by janschulte** [comment]
Oh, I missed this. What should be presented instead? Only the ones with values at 14h?

**Comment by opeeters** [comment]
the closest station that has data for the last hour (cf last update). But see issue  #60

**Comment by janschulte** [comment]
Fixed with: 852faede5cfd67d6023aaebc815241240b1cc71a

**Comment by opeeters** [comment]
yes!
