### ISSUE TITLE
last update value remains at 02h00

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#60]
Even when http://www.irceline.be/air/time_app_json.php lists the correct last update, the last update at the top of the start page remains at 02h00:

![screenshot_20181017-152504](https://user-images.githubusercontent.com/323719/47089449-2a494a00-d221-11e8-92e7-9b2a6f86db10.png)

**Comment by opeeters** [comment]
This might explain the wrong value being listed in nearest station banner.. see issue #59

**Comment by janschulte** [comment]
This was just a wrong time format fixed with: 332906e750fd557392cb18eecf1d98095a338088

14 PM -> 02 AM, now the time is presented in 24h format

**Comment by opeeters** [comment]
Oh, my mistake when I tried to get rid of the seconds as in `date: 'medium'`. Sorry.
