### ISSUE TITLE
add toggle `current location` to last slide on start page

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#61]
Add toggle `current location` to last slide on start page.
This is also convenient when user does not add a location during first run wizard.

**Comment by janschulte** [comment]
But on which slide should the current location appear? I don't see a good solution to let the user decide, where the current location should be displayed...

**Comment by opeeters** [comment]
by default as first slide, or respecting the order as set via the `edit current locations` list

**Comment by janschulte** [comment]
Added with f08e29666028ddc0817e6acd9a3fd890f6081d38
