### ISSUE TITLE
position of device is not taken from location service

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#62]
Every now and again (it seems every second launch), on app launch with location service enabled, the message "Geolocation is disabled" is displayed and no index wheel for configured locations is display. Only relaunching the app fixes the problem.

![screenshot_20181018-100610](https://user-images.githubusercontent.com/323719/47140057-a2fde400-d2bd-11e8-9f7b-91b4b790b373.png)

**Comment by opeeters** [comment]
I just released `0.5.3` with f08e29666028ddc0817e6acd9a3fd890f6081d38. I have not yet experienced the same issue. Fingers crossed :-)

**Comment by janschulte** [comment]
New fixes with: 42ffde8e7b11e84beb15d200d462d68d61e0fd35

**Comment by opeeters** [comment]
even after deleting all configured locations I get empty screens as soon as "current location" is activated:

![screenshot_20181109-143840](https://user-images.githubusercontent.com/323719/48265705-7a38bc80-e42d-11e8-941b-78e6aaa149e8.png)

**Comment by opeeters** [comment]
The good news is that the bug does not block everything. This is certainly progress. However, on my device, the location from the location service of the device does not seem to get through. When "current location" is activated, I get an eternal spinning wheel of joy on the slide of the current location:

![screenshot_20181111-134526](https://user-images.githubusercontent.com/323719/48313137-505fd100-e5b8-11e8-8e83-0828be00ed92.png)

But I can still slide to the other configured locations.

**Comment by janschulte** [comment]
I switched the location determination to high accuracy (491718a0ca7b176853a277d35d842bdb80d9cd99) and add some information which is the state of the location process. Is it working now, what notifications did you see? Are there some errors displayed?

**Comment by opeeters** [comment]
The high accuracy clearly works much better on my device. I occasionally get the following error message:
```
Location-Error:[ObjectPositionError]
```
This is only temporary though. After a couple of seconds a position is established and the correct data is displayed on the slide.

Occasionally, on app launch after closing the app with "current location" enabled, the app only displays the last slide:

![screenshot_20181112-010754](https://user-images.githubusercontent.com/323719/48320242-86806d80-e617-11e8-8657-7b63db03a1bc.png)

Notice how the geoposition icon is red even though the location service of the device is enabled.
This only seems to happen when you have "current location" enabled and the location service of your device enabled, you switch to another app, disable location service of your device and launch BelAir again.

**Comment by janschulte** [comment]
Great, but I can't reconstruct the other two points you mentioned. 

I add a resume listener (1f9de584fb59aefeb5f119e97dc70f3838d54ad7), which triggers the geolocation check, when the app comes back to foreground. Hopefully this fixes the second point.

And the a question to the first point, did you only use the current location or are there also user configured location? Or is this happen in both states (with and without user configured locations)?

**Comment by opeeters** [comment]
In answer to the question.. I only had this when I also had a user configured location. I tried to trigger the same error when no user configured location was saved. The error does not appear in that state.

**Comment by opeeters** [comment]
After the changes in 9bfc23b8c9dfb7dc089e39cb8f5984c950283906 I get this when no user locations are configured:

![screenshot_20181116-101640](https://user-images.githubusercontent.com/323719/48612361-17917480-e989-11e8-87d0-93b14c0a7809.png)

In this case the location service of the device was enabled, but "current location" in the app disbled.

**Comment by janschulte** [comment]
I could reconstruct the last two issue and fixed them with: 77270c4906b6945d82e9fdf4c9fdc440f3c8ab33

**Comment by opeeters** [comment]
These two issues are indeed fixed. The following bug remains:
Steps to reproduce:
- launch app and configure at least one personal location
- activate "current location"
- close app
- launch app with location service of the device enabled in a situation where your location cannot be established (e.g. in the elevator with `location` of the device set to `device only` or on a trein)

The app will hang in this state:

![screenshot_20181119-100741](https://user-images.githubusercontent.com/323719/48699199-2e360680-ebe9-11e8-857f-ae2950859a09.png)

Expected result:
Even if the location cannot be established, the configured locations should be accessible. I will also add a separate issue to improve the messages displayed in the app in cases where the location is not established fast enough. This is rather an enhancement than a bug..

**Comment by opeeters** [comment]
I just notice that if you open google maps with the location service set to `device only` in a situation where you do have network connectivity but no gps signal, the app asks you to activate the `google location service` (probably just `high accuracy` mode). Could this also be possible in an ionic app? E.g. with this plugin: https://ionicframework.com/docs/native/location-accuracy/

**Comment by opeeters** [comment]
All seems well with 0.6.3
I will close the issue. The idea concerning switching to `high accuracy` from within the app has been moved to issue #79
