### ISSUE TITLE
air quality text inside wheel too big

### ISSUE THREAD

**Issue by d-roet** [irceline/aq-mobile-be#63]
sometimes, like yesterday, the (dutch) larger text (like "middelmatig) inside the air quality wheel falls outside of the black border of the dial. perhaps this is a scaling issue on some devices?

I did not take a screenshot .. but hopefully it is clear what I mean ...

**Comment by opeeters** [comment]
Should be fixed in version 0.5.2. Update via play store if automatic update has not been triggered yet on your device

**Comment by d-roet** [comment]
I updated to 0.5.2 but can't confirm yet if the issue is fully resolved. So far I haven't had "middelmatig" air quality, but I will keep an eye on it and let you know,
