### ISSUE TITLE
add annual mean evaluation to items in `location list`

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#65]
In the `location list`, under each map of every configured location, add five buttons (BC, NO2, O3, PM10 and PM2.5) pointing to an annual mean map viewer (similar to map-page, call it e.g. annual-map-page).

Take last update year from here:
http://www.irceline.be/air/timestring_rioifdm_anmean.php

The map layers to be used are the following:
http://geo.irceline.be/rioifdm/bc_anmean_2016/wms?service=WMS&version=1.3.0&request=GetCapabilities
http://geo.irceline.be/rioifdm/no2_anmean_2016/wms?service=WMS&version=1.3.0&request=GetCapabilities
http://geo.irceline.be/rioifdm/o3_anmean_2016/wms?service=WMS&version=1.3.0&request=GetCapabilities
http://geo.irceline.be/rioifdm/pm25_anmean_2016/wms?service=WMS&version=1.3.0&request=GetCapabilities
http://geo.irceline.be/rioifdm/pm10_anmean_2016/wms?service=WMS&version=1.3.0&request=GetCapabilities

Legends:
http://www.irceline.be/air/legend/bc_anmean_EN.svg
etc.

On the top of the page there should be a link back to location list (e.g. instead of last update widget).

**Comment by janschulte** [comment]
I am a bit confused about the location where the buttons should appear. Can you give me a screenshot? As far as I understand it should be here, but is this really the right place? At this place I only see slight configuration an no way to get extra information...

<img src="https://user-images.githubusercontent.com/3830314/47341076-58ef7680-d6a0-11e8-9bb3-1ea48724d721.png" width="300" />

**Comment by opeeters** [comment]
Where you indicate is indeed the place I had in mind. Let's try this. So within the <ion-item> of the location. Five buttons as on the start page. With only colour according to anmean concentration class.

The reason why we would keep it there, in the configuration, is to avoid confusion with hourly maps. But, on the start page there is a link (last slide) to this location list. I think it might make sense after all..

**Comment by janschulte** [comment]
Done with 013e172082fd9c779d083361479a939479ee5f49

**Comment by opeeters** [comment]
Can you please add a `getFeatureInfo` request and color the buttons with the corresponding index color. These are the relevant annual concentration classes:

http://www.irceline.be/air/legend/bc_anmean_EN.svg
http://www.irceline.be/air/legend/no2_anmean_EN.svg
http://www.irceline.be/air/legend/o3_anmean_EN.svg
http://www.irceline.be/air/legend/pm10_anmean_EN.svg
http://www.irceline.be/air/legend/pm25_anmean_EN.svg

Also, please add a map.configured-location pop-up.

**Comment by opeeters** [comment]
Also, please add zoom functionality (cf the nearest station zoom) with only one info balloon "Your configured location".
