### ISSUE TITLE
zoom to `nearest station` when going to map page via nearest station buttons

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#66]
zoom to `nearest station` when going to map page via nearest station buttons. Let's start with zoom level `14` on the lat/long of the relevant nearest station.

**Comment by opeeters** [comment]
Excellent!
To make it more user friendly, add marker with i18n description `your configured location` (or `your location` if you come from the `current location` state). This marker should be closable or even removable (whatever is easier for the time being).

**Comment by janschulte** [comment]
Done with e1b38aafa5890a5fab02c546cfa1e93898860c50
