### ISSUE TITLE
move geolocation disabled/enabled to a button in the navbar

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#67]
Move geolocation disabled/enabled message to a button in the navbar (e.g. the `locate` icon from the ionic framework) and change the colour of the icon to green (`#00FF00`) - `enabled` and red (`#FF0000`) - `disabled`. Add a little message call-out on state change ( {{network.geolocationDisabled | translate}} and {{network.geolocationEnabled | translate}}.

**Comment by janschulte** [comment]
Done with: b52dcf5e02944b284d6b4e86b5507dfd95f2f5a6

**Comment by opeeters** [comment]
Please add tooltip (cf {{network.geolocationDisabled}}/{{network.geolocationEnabled}}) when clicking on icon.

**Comment by opeeters** [comment]
see 1f7838153112884989e8b55d1044d6cf7c30346e
