### ISSUE TITLE
Add info pop-up to index wheel

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#69]
Add info pop-up to index wheel, e.g. top right corner of belaqi-wheel (using the ionic `information-circle` icon). The message displayed should be {{info.wheel.message}}. Under the message should be a `more info` link text or button (use {{info.moreInfo}}) which opens {{info.wheel.link}}. Would it maybe be a good idea to make use of `ionic-native/in-app-browser` for this?

**Comment by opeeters** [comment]
see 68fc77bf4d44c2014ca169982b5b4512e141a648

Also `belaqiInformationUrl` needs to be translated. Hence I added a {{info.wheel.link}} which was removed with the above commit.

**Comment by janschulte** [comment]
Fixed with: 3053ef8b2adc84337379b337ec2fd687a2c0296b
