### ISSUE TITLE
message when location is deactivated on device

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#7]
When location on a smartphone is deactivated, "loading modelled value..." is displayed. It would be preferable to make a distinction here between e.g.: "loading" and "the location of your device is unknown since the location service is deactivated", or something along these lines...

**Comment by opeeters** [comment]
additionally, when location is activated on a device, the modelled value and nearest station is not fetched.

**Comment by opeeters** [comment]
a refresh button would be useful

**Comment by janschulte** [comment]
Add a refresh button with f52dd45cbd56334a4ae7c3d3f5a9b64dcce7ed72 and a check if geolocation is active with 1cdb2738d0aa9883fa8bdc196f33b79ba093e051
