### ISSUE TITLE
legends annual mean maps are not changed when switching tabs

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#71]
The legends of the annual mean maps are not changed when going from one tab to the next when the legend has been expanded. The legend remains the legend of the origin pollutant being used to access the viewer. So, entering via the BC button, the expanded legend remains the BC-legend even when going to the PM25 tab.
Probably a `this.legend.remove();` needs to be added to the event of changing tabs + an event adding the right legend.

**Comment by janschulte** [comment]
Done with: 1a1a0e218b54a04a2d670a2b57deb613496a0859

**Comment by opeeters** [comment]
Add similar functionality on the map page. Currently the legend is closed on tab change. It would be better if legend would remain open and content would be changed (similar to annual map viewer).

**Comment by opeeters** [comment]
done with 39f42629be1f43ee12bf436a3d1c38fe712482d4
