### ISSUE TITLE
change font y-axis diagram

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#73]
Change font label y-axis to `roboto` and reduce size:

<img width="364" alt="screenshot 2018-11-06 at 15 19 00" src="https://user-images.githubusercontent.com/323719/48070138-76abf800-e1d7-11e8-8135-2a34dde944b2.png">

**Comment by janschulte** [comment]
Done with: 49a5d4dc76836095f1ec9a166046e7bbfa455128
