### ISSUE TITLE
put BC on different y-axis

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#74]
In the diagram view put BC on a separate y-axis. Since BC is always much lower than the other pollutants, important relative spikes are not visible otherwise.

**Comment by janschulte** [comment]
Done with: 60b1b94beb0c048db8529543902d23596cf322a4

**Comment by opeeters** [comment]
BC on separate axis has been temporarily been disabled until fully functional. See 90ac7e75e223e860bfa0d4e235a305c9732f0a8f

**Comment by janschulte** [comment]
reenabled  with new toolbox version: 2dd8b597d0c1af50739522aadde8f99002e17e96
