### ISSUE TITLE
No data message forecast maps

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#75]
Two issues:
1) before noon the day+3 map is often not available. Please add message "Currently there is no data available. Try again after 13h00." When there is no data layer available
2) When the `other` tab is selected, no map should be in the map and the forecast tabs should be tinted (cf when the BC tab is active).

**Comment by janschulte** [comment]
Done Part 2 with: 57d17ce68afaa21ab3f4115201e4529d3e7221a9
