### ISSUE TITLE
Add legend for "other" pollutants

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#76]
Add legend for "other" pollutants where possible. The following legends are available:

CO: http://www.irceline.be/air/legend/co_hmean_EN.svg
SO2: http://www.irceline.be/air/legend/so2_hmean_EN.svg
Benzene: http://www.irceline.be/air/legend/c6h6_24hmean_EN.svg

When no legend is available, display a message in the legend pop-up: "no legend available"

**Comment by janschulte** [comment]
Done with: 0171dd730c3e4cfd023034c3a26c784019d3f907
