### ISSUE TITLE
Add option to store your current location

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#77]
In "Create new location", add an option to store your current location (taken from your device location service) as a location as part of your location list. So that even when you are elsewhere you can consult this location..

**Comment by janschulte** [comment]
Done with: 5fa2a5ed736b8c4166cd683ac82d9e05c05b8a60

**Comment by opeeters** [comment]
There are some issues with the implementation of this functionality.

1) When location service of device is deactivated, a warning should be displayed after clicking `create new location` > `use current location` (cf geolocation is disabled warnings, incl. time-out when location cannot be established)

2) Editing name of location directly is buggy.
Steps to reproduce:
- `create new location` > `use current location`
- click `X` to change the entire label -> input dialog disappears
It is however possible to change label by deleting letter per letter or by first adding and later editing via `edit current locations`

**Comment by janschulte** [comment]
Fixed with: 5d86399d67c7a6294118c6b39f7e1be5d60f3cc2
