### ISSUE TITLE
improve error messages when loction of device cannot be established

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#79]
The following suggestions:
1) When the device is taking longer than 3 seconds to establish location (with `current location` enabled and custom user locations present), display a message instructing user to swipe to the right to see data from the configured location.
2) When the device is taking longer than 3 seconds to establish location change color of location icon to red and display a different message in the tooltip. E.g.: "Your device is taking some time to establish your location. Make sure that the location service of your device is set to "high accuracy" for best results or add your location manually here: {{create new location}}-button.

**Comment by opeeters** [comment]
Point 1 has been implemented with ee3bbf141edae025bdda49ba48beb412031f75f3
Point 2 should still be implemented, e.g. using https://ionicframework.com/docs/native/location-accuracy/

**Comment by janschulte** [comment]
Add as discussed by mail and telco a traffic light specific solution to show the state of the geolocation with ce6ee21133f04022656601cbd994abc81a22c840
