### ISSUE TITLE
double station layer on map page

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#8]
There is both a selectable layer of data coming from the REST-api and a WMS layer on the map page. This should only be the layer with data coming from the REST-api..

**Comment by janschulte** [comment]
Fixed with commit 14fe6d5eac4c1c093712217d531976ef9a7b4805

Add `stations` parameter to `settings.json` for all stationary layers which shouldn't be present in the map view, where the stations are presented by clickable markers.
