### ISSUE TITLE
add language to nominatim call

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#84]
Add language to nominatim call when user adds location. See [https://wiki.openstreetmap.org/wiki/Nominatim#Address_lookup](https://wiki.openstreetmap.org/wiki/Nominatim#Address_lookup)
e.g. with `accept-language=`. When user adds e.g. `Arlon` with app set to French, `Arlon` should be returned, not `Aarlen`.

**Comment by janschulte** [comment]
Done with: 6a125addb03480378bdb35da8bddf490b4cece2d
