### ISSUE TITLE
automatically go to slide with data when location is not established before timeout

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#85]
When "current location" is activated and the location is not established before the timeout the app remains on the slide where the "current location" data is to be displayed with the `belaqi-user-location-slider.current-location-error` message being displayed. 
It would be more user friendly to either switch to the top slide with data automatically in the case that the user has already configured (multiple) user locations or to display the "create location" button to invite the user to manually configure a location.
Also, the timeout should maybe better be set to 15 seconds. It currently takes a bit to long.

**Comment by janschulte** [comment]
Done with: 9b9f3b6d6a412931805f905ce02537d15cafe28b
