### ISSUE TITLE
revamp styling belaqi-wheel

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#86]
The index text should always be perfectly aligned in the horizontal an vertical center.
The little marker arrow is slightly off for the higher index classes.

**Comment by janschulte** [comment]
Done with: e74e080f7949d8afbd980a2fab422f5c891ac252 and 6284f0817de79a7cf79078ac9d44d693ff76fdd1

**Comment by opeeters** [comment]
The marker arrow seems fine now.
The text is often still slightly of center.

**Comment by janschulte** [comment]
Readjust the centering with: f2ea9adbc0e5c8344fea132154e2d11ae00f2c20
