### ISSUE TITLE
wrong colour dots in belaqi-chart

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#87]
all dots in `belaqi-chart` are coloured with the index colour of index class 10 both in `master` and `feature/upgrade` branch:

![screenshot_20190107-142113](https://user-images.githubusercontent.com/323719/50770502-db430c00-1287-11e9-844e-882c921dbece.png)

**Comment by opeeters** [comment]
temp fix see: 32278d0535bf601291723c1fd1f17bf4404a9a9c

**Comment by opeeters** [comment]
In conjunction with a permanent fix that also works with chart.js 2.7.3, the dots should become uni-coloured and not have a gradient in them.

**Comment by janschulte** [comment]
fixed with: b973da6e2278849c00bcc01e3e6c58b5353e0a4e
