### ISSUE TITLE
styling station icons map view

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#88]
1) change `NaN` fill color station dot in map view from `#000` to `#FFF`
2) resize icons when zooming in (see e.g. https://gis.stackexchange.com/questions/216558/leaflet-resize-markers-in-layer-when-zoom-in/216561) - when zoomed in the current size is OK (22.85px), when zoomed out to full extend they should be no bigger than 6px

**Comment by janschulte** [comment]
Add functionality with: c17abe9d2f3740fb1992ada1ccd55f04e2ccc290
But i will try to move these configuration to the toolbox in the next days. Please leave open until this is done.
