### ISSUE TITLE
height of slides

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#89]
The height of slides is sometimes not correct. See e.g.:

![screenshot_20190112-135810](https://user-images.githubusercontent.com/323719/51073628-2e480500-1674-11e9-8288-8f621709c3fc.png)

The 3 blue dots are above the last line of text. For this message this is always the case.

This also sometimes happens on other location slides, but I cannot consistently reproduce this behaviour.

**Comment by opeeters** [comment]
Partially solved with: 59a42dc
It would be better if height of slide is dynamically established (cf index slides).

**Comment by janschulte** [comment]
Should be fixed with: 511593226b88ad01ac9130decaaceb9d934d0f86
