### ISSUE TITLE
app stopped working

### ISSUE THREAD

**Issue by d-roet** [irceline/aq-mobile-be#94]
With the latest version of the app (`0.6.7`) on Android 8.1 I get this error message each time I try to switch to another app window. See attached screenshots.

![screenshot_20190115-161949](https://user-images.githubusercontent.com/44231269/51190156-e0383900-18e1-11e9-9917-d7f8549701e7.png)

**Comment by opeeters** [comment]
@d-roet is this still an issue with the public release of 0.6.7? Uninstall and reinstall..

**Comment by opeeters** [comment]
Only seen on `Motorola Moto G5`. Or has anyone experienced this on a different device?

**Comment by d-roet** [comment]
@opeeters the issue still persists in the latest version of the app (0.6.8). I performed an `adb logcat` on my device and I believe the relevant error in the log to be:

```
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification:
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6626)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
  Force finishing activity be.irceline.aqmobile/.MainActivity
Displayed com.android.systemui/.recents.RecentsActivity,wp,wa,103
Showing crash dialog for package be.irceline.aqmobile u0
```

I think it has to do with Android 8.1, since I updated the OS on my phone this issue appeared. I did a quick search on the error `java.lang.RuntimeException: invalid channel for service notification` and found this post which might be helpful 
(https://stackoverflow.com/questions/47531742/startforeground-fail-after-upgrade-to-android-8-1)

HTH

**Comment by simonjirka** [comment]
This might be an issue with the background mode plugin for cordova. In the following issue a possible solution is discussed. We will have a closer look at this: https://github.com/katzer/cordova-plugin-background-mode/issues/393

**Comment by DevlprArup** [comment]
I was facing the same issue for over an week and found no solution. Finally, I took the following steps:

1. Removed the `plugin ` with the associated  `npm-package` 
2. Uninstalled platform. In my case it was `Android`
3. Ran `npm cache clean`
4. Reinstalled the `android platform` 
5. Reinstalled the `plugin` and not the Ionic prescribed `npm wrapper`.
6. To avoid `Typescript` error - used `declare var cordova: any;` 
7. Then simply went on to implement the code as described in the respective Cordova Plugin doc. The steps are as follows

A. I wanted to use `https://ionicframework.com/docs/v3/native/background-mode/` so I headed over to the associated repo at: `https://github.com/katzer/cordova-plugin-background-mode/blob/master/README.md`

B. install the latest head version -
`cordova plugin add https://github.com/katzer/cordova-plugin-background-mode.git`

C. Imported the plug in at `module` & `component` .ts - 
`import { BackgroundMode } from '@ionic-native/background-mode';`

D. Defined `declare var cordova: any;` at `component.ts`

E. Implemented the code **EXACTLY** as shown in `https://github.com/katzer/cordova-plugin-background-mode/tree/example` - 

```js
private enable_background_mode() {
    //
    let options = {
      title: 'Your-desired-title',
      text: 'Your-desired-text',      
      color: 'FF0000',
      hidden: false,
    }
    cordova.plugins.backgroundMode.setDefaults(options);
    //
    cordova.plugins.backgroundMode.on('activate', () => {
      console.log('background mode activated ');      
    });
    //
    cordova.plugins.backgroundMode.enable();
  }
```

That's all.

**Comment by opeeters** [comment]
Thanks allot @DevlprArup for the feedback! Looks promising. I did not have time during the weekend to look into this. New feature development was more urgent.. @janschulte please have a look at this.

**Comment by Entrecampos** [comment]
@katzer Any chance on this solution be added to the main repo code?

**Comment by Entrecampos** [comment]
I installed 

https://github.com/lkonzen-garupa/cordova-plugin-background-mode

[and add the code for wake_lock](https://github.com/katzer/cordova-plugin-background-mode/issues/400#issuecomment-484077499)

Is working for android 5, 7 and 10 :-)
