### ISSUE TITLE
differentiate belaqi-wheel.no-index-ascertained

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#97]
The `belaqi-wheel.no-index-ascertained` message needs to be differentiated into a check whether there is no index value returned because a user is outside of Belgium. In such a case the `GetFeatureInfo` would return:

```
{

    "type": "FeatureCollection",
    "features": [ ]

}
```
For this the current message is fine.

... or whether there is no return to the `GetFeatureInfo` due to server overload. A more telling message should be displayed in the later case, e.g.:
```
It is taking longer than usual to fetch the data. Please try again later.
```

There is also the case where data is slow to load due to a client being on a very slow (mobile) network. Is it possible to detect this situation to fire a more telling message in such a case?

**Comment by janschulte** [comment]
Adjusted with: 28e8bd366214e5925937ee6785e6b6f516f46d2b

I also added a loading hint at the place of the wheel, when the data fetching is slow. But a detection of a slow mobile connection isn't so easy.
